using LankaSaaS.Application;using LankaSaaS.Domain;using LankaSaaS.Infrastructure;using Microsoft.EntityFrameworkCore;
public static class AccountingEndpoints
{
 public static void Map(WebApplication app){var g=app.MapGroup("/api/accounting");g.MapGet("/accounts",Accounts).RequireAuthorization(Permissions.AccountingView);g.MapGet("/journals",Journals).RequireAuthorization(Permissions.AccountingView);g.MapPost("/journals",Manual).RequireAuthorization(Permissions.AccountingPostJournals).AddEndpointFilter<ValidationFilter>();g.MapPost("/migration/opening-balances",ImportOpeningBalances).RequireAuthorization(Permissions.AccountingPostJournals).AddEndpointFilter<ValidationFilter>();g.MapGet("/profit-loss",ProfitLoss).RequireAuthorization(Permissions.AccountingView);}
 static async Task<IResult> Accounts(AppDbContext db,ITenantContext tenant,CancellationToken ct){await AccountingService.EnsureAccounts(db,tenant,ct);var values=await db.JournalLines.GroupBy(x=>x.AccountId).Select(x=>new{x.Key,Debit=x.Sum(y=>y.Debit),Credit=x.Sum(y=>y.Credit)}).ToDictionaryAsync(x=>x.Key,ct);var rows=await db.LedgerAccounts.OrderBy(x=>x.Code).ToListAsync(ct);return Results.Ok(rows.Select(x=>{var v=values.GetValueOrDefault(x.Id);var balance=x.Type is AccountTypes.Asset or AccountTypes.Expense?v?.Debit-v?.Credit:v?.Credit-v?.Debit;return new LedgerAccountDto(x.Id,x.Code,x.Name,x.Type,x.IsSystem,x.IsActive,balance??0);}));}
 static async Task<IResult> Journals(Guid? eventId,AppDbContext db,CancellationToken ct){var q=db.JournalEntries.AsNoTracking().AsQueryable();if(eventId.HasValue)q=q.Where(x=>x.EventId==eventId);return Results.Ok(await q.OrderByDescending(x=>x.EntryDate).ThenByDescending(x=>x.CreatedAt).Take(200).Select(x=>new JournalEntryDto(x.Id,x.EntryDate,x.Description,x.Reference,x.EventId,x.SourceType,x.Lines.Select(l=>new JournalLineDto(l.AccountCode,l.AccountName,l.Debit,l.Credit)).ToList())).ToListAsync(ct));}
 static async Task<IResult> Manual(ManualJournalRequest r,AppDbContext db,ITenantContext tenant,CancellationToken ct){if(r.Lines is null||r.Lines.Count<2||r.Lines.Any(x=>(x.Debit>0)==(x.Credit>0))||r.Lines.Sum(x=>x.Debit)!=r.Lines.Sum(x=>x.Credit)||r.Lines.Sum(x=>x.Debit)<=0)return Results.BadRequest(new{message="Journal lines must contain equal positive debits and credits."});if(r.EventId.HasValue&&!await db.Events.AnyAsync(x=>x.Id==r.EventId,ct))return Results.BadRequest(new{message="Event was not found."});await AccountingService.EnsureAccounts(db,tenant,ct);var ids=r.Lines.Select(x=>x.AccountId).Distinct().ToList();var accounts=await db.LedgerAccounts.Where(x=>ids.Contains(x.Id)&&x.IsActive).ToDictionaryAsync(x=>x.Id,ct);if(accounts.Count!=ids.Count)return Results.BadRequest(new{message="An account was not found or is inactive."});var sourceId=Guid.NewGuid();var entry=new JournalEntry{TenantId=tenant.TenantId,EntryDate=r.EntryDate,Description=r.Description.Trim(),Reference=r.Reference?.Trim(),EventId=r.EventId,SourceType="Manual",SourceId=sourceId,Lines=r.Lines.Select(x=>new JournalLine{TenantId=tenant.TenantId,AccountId=x.AccountId,AccountCode=accounts[x.AccountId].Code,AccountName=accounts[x.AccountId].Name,Debit=x.Debit,Credit=x.Credit}).ToList()};db.JournalEntries.Add(entry);await db.SaveChangesAsync(ct);return Results.Created($"/api/accounting/journals/{entry.Id}",entry.Id);}
 static async Task<IResult> ImportOpeningBalances(AccountingImportRequest r,AppDbContext db,ITenantContext tenant,CancellationToken ct)
 {
  var validTypes=new HashSet<string>([AccountTypes.Asset,AccountTypes.Liability,AccountTypes.Equity,AccountTypes.Revenue,AccountTypes.Expense],StringComparer.OrdinalIgnoreCase);
  var rows=r.Lines.Select(x=>new{Code=x.AccountCode.Trim(),Name=x.AccountName.Trim(),Type=x.AccountType.Trim(),x.Debit,x.Credit}).ToList();
  if(rows.Count<2||rows.Count>500)return Results.BadRequest(new{message="Import between 2 and 500 account rows."});
  if(rows.Any(x=>string.IsNullOrWhiteSpace(x.Code)||string.IsNullOrWhiteSpace(x.Name)||!validTypes.Contains(x.Type)||(x.Debit>0)==(x.Credit>0)))return Results.BadRequest(new{message="Every row needs a valid account, type and either a debit or credit amount."});
  if(rows.GroupBy(x=>x.Code,StringComparer.OrdinalIgnoreCase).Any(x=>x.Count()>1))return Results.BadRequest(new{message="Account codes must be unique within the import file."});
  var debit=rows.Sum(x=>x.Debit);var credit=rows.Sum(x=>x.Credit);
  if(debit<=0||debit!=credit)return Results.BadRequest(new{message=$"Opening balances must balance. Debit: {debit:0.00}; Credit: {credit:0.00}."});
  var reference=r.ImportReference.Trim();
  await using var tx=await db.Database.BeginTransactionAsync(ct);
  await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtext({tenant.TenantId+":"+reference}))",ct);
  if(await db.JournalEntries.AnyAsync(x=>x.SourceType=="OpeningBalanceImport"&&x.Reference==reference,ct))return Results.Conflict(new{message="This import reference has already been posted."});
  await AccountingService.EnsureAccounts(db,tenant,ct);
  var codes=rows.Select(x=>x.Code).ToList();var accounts=await db.LedgerAccounts.Where(x=>codes.Contains(x.Code)).ToDictionaryAsync(x=>x.Code,StringComparer.OrdinalIgnoreCase,ct);var created=0;
  foreach(var row in rows){if(accounts.TryGetValue(row.Code,out var existing)){if(!existing.IsActive||!string.Equals(existing.Type,row.Type,StringComparison.OrdinalIgnoreCase))return Results.Conflict(new{message=$"Account {row.Code} exists with a different type or is inactive."});continue;}var account=new LedgerAccount{TenantId=tenant.TenantId,Code=row.Code,Name=row.Name,Type=validTypes.Single(x=>string.Equals(x,row.Type,StringComparison.OrdinalIgnoreCase)),IsSystem=false};db.LedgerAccounts.Add(account);accounts[row.Code]=account;created++;}
  var entry=new JournalEntry{TenantId=tenant.TenantId,EntryDate=r.OpeningDate,Description="Imported opening balances",Reference=reference,SourceType="OpeningBalanceImport",SourceId=Guid.NewGuid(),Lines=rows.Select(x=>new JournalLine{TenantId=tenant.TenantId,AccountId=accounts[x.Code].Id,AccountCode=x.Code,AccountName=accounts[x.Code].Name,Debit=x.Debit,Credit=x.Credit}).ToList()};
  db.JournalEntries.Add(entry);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Results.Created($"/api/accounting/journals/{entry.Id}",new AccountingImportResultDto(entry.Id,created,rows.Count,debit,credit));
 }
 static async Task<IResult> ProfitLoss(DateOnly? from,DateOnly? to,Guid? eventId,AppDbContext db,CancellationToken ct){var today=BusinessClock.Today;var start=from??new DateOnly(today.Year,1,1);var end=to??today;if(end<start)return Results.BadRequest(new{message="The end date cannot be before the start date."});var q=db.JournalEntries.Where(x=>x.EntryDate>=start&&x.EntryDate<=end);if(eventId.HasValue){if(!await db.Events.AnyAsync(x=>x.Id==eventId,ct))return Results.NotFound();q=q.Where(x=>x.EventId==eventId);}var lines=q.SelectMany(x=>x.Lines);var revenue=await lines.Where(x=>x.AccountCode==SystemAccountCodes.EventRevenue).SumAsync(x=>(decimal?)(x.Credit-x.Debit),ct)??0;var expense=await lines.Where(x=>x.AccountCode==SystemAccountCodes.EventExpenses).SumAsync(x=>(decimal?)(x.Debit-x.Credit),ct)??0;return Results.Ok(new ProfitLossDto(start,end,revenue,expense,revenue-expense));}
}
