using LankaSaaS.Application;
using LankaSaaS.Domain;
using LankaSaaS.Infrastructure;
using Microsoft.EntityFrameworkCore;

public static class EventEndpoints
{
    static readonly string[] Statuses=[EventStatuses.Planning,EventStatuses.Confirmed,EventStatuses.InProgress,EventStatuses.Completed,EventStatuses.Cancelled];
    public static void Map(WebApplication app){var g=app.MapGroup("/api/events").RequireAuthorization();g.MapGet("/",List);g.MapGet("/{id:guid}",async(Guid id,AppDbContext db)=>await Load(id,db) is{} x?Results.Ok(x):Results.NotFound());g.MapPost("/",Create).AddEndpointFilter<ValidationFilter>();g.MapPut("/{id:guid}",Update).AddEndpointFilter<ValidationFilter>();g.MapPost("/{id:guid}/expenses",AddExpense).AddEndpointFilter<ValidationFilter>();g.MapDelete("/{id:guid}/expenses/{expenseId:guid}",RemoveExpense);}
    static async Task<IResult> List(AppDbContext db){var events=await db.Events.OrderBy(x=>x.StartsAt).ToListAsync();var expenses=await db.Expenses.Where(x=>x.EventId!=null).ToListAsync();return Results.Ok(events.Select(x=>ToDto(x,expenses.Where(e=>e.EventId==x.Id).AsQueryable())).ToList());}
    static async Task<IResult> Create(EventRequest r,AppDbContext db){var validation=await Validate(r,db);if(validation is not null)return validation;var customer=await db.Customers.SingleAsync(x=>x.Id==r.CustomerId);var x=new BusinessEvent{CustomerId=customer.Id,CustomerName=customer.Name,Name=r.Name.Trim(),Venue=r.Venue.Trim()};Apply(x,r);db.Events.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/events/{x.Id}",await Load(x.Id,db));}
    static async Task<IResult> Update(Guid id,EventRequest r,AppDbContext db){var validation=await Validate(r,db);if(validation is not null)return validation;var x=await db.Events.SingleOrDefaultAsync(x=>x.Id==id);if(x is null)return Results.NotFound();var customer=await db.Customers.SingleAsync(x=>x.Id==r.CustomerId);x.CustomerId=customer.Id;x.CustomerName=customer.Name;x.Name=r.Name.Trim();x.Venue=r.Venue.Trim();Apply(x,r);await db.SaveChangesAsync();return Results.Ok(await Load(id,db));}
    static async Task<IResult> AddExpense(Guid id,EventExpenseRequest r,AppDbContext db,ITenantContext tenant){if(!await db.Events.AnyAsync(x=>x.Id==id))return Results.NotFound();await using var tx=await db.Database.BeginTransactionAsync();var x=new Expense{EventId=id,Description=r.Description.Trim(),Category=r.Category.Trim(),Amount=r.Amount,ExpenseDate=r.ExpenseDate};db.Expenses.Add(x);await AccountingService.Post(db,tenant,r.ExpenseDate,x.Description,"EventExpense",x.Id,id,null,[(SystemAccountCodes.EventExpenses,r.Amount,0),(SystemAccountCodes.Cash,0,r.Amount)]);await db.SaveChangesAsync();await tx.CommitAsync();return Results.Created($"/api/events/{id}/expenses/{x.Id}",new EventExpenseDto(x.Id,x.Description,x.Category,x.Amount,x.ExpenseDate));}
    static async Task<IResult> RemoveExpense(Guid id,Guid expenseId,AppDbContext db,ITenantContext tenant){var x=await db.Expenses.SingleOrDefaultAsync(x=>x.Id==expenseId&&x.EventId==id);if(x is null)return Results.NotFound();if(x.PurchaseOrderId.HasValue||x.EventStaffAssignmentId.HasValue)return Results.Conflict(new{message="Generated expenses must be managed from their source module."});await using var tx=await db.Database.BeginTransactionAsync();await AccountingService.Post(db,tenant,BusinessClock.Today,$"Reversal: {x.Description}","EventExpenseReversal",x.Id,id,null,[(SystemAccountCodes.Cash,x.Amount,0),(SystemAccountCodes.EventExpenses,0,x.Amount)]);db.Expenses.Remove(x);await db.SaveChangesAsync();await tx.CommitAsync();return Results.NoContent();}
    static async Task<IResult?> Validate(EventRequest r,AppDbContext db){if(r.CustomerId==Guid.Empty||!await db.Customers.AnyAsync(x=>x.Id==r.CustomerId))return Results.BadRequest(new{message="Select a valid customer."});if(r.EndsAt<=r.StartsAt)return Results.BadRequest(new{message="Event end must be after its start."});if(!Statuses.Contains(r.Status))return Results.BadRequest(new{message="Select a valid event status."});return null;}
    static void Apply(BusinessEvent x,EventRequest r){x.StartsAt=r.StartsAt;x.EndsAt=r.EndsAt;x.Status=r.Status;x.BudgetedRevenue=r.BudgetedRevenue;x.BudgetedCost=r.BudgetedCost;x.Notes=string.IsNullOrWhiteSpace(r.Notes)?null:r.Notes.Trim();}
    static async Task<EventDto?> Load(Guid id,AppDbContext db){var x=await db.Events.SingleOrDefaultAsync(x=>x.Id==id);if(x is null)return null;var expenses=await db.Expenses.Where(e=>e.EventId==id).ToListAsync();return ToDto(x,expenses.AsQueryable());}
    static EventDto ToDto(BusinessEvent x,IQueryable<Expense> expenses)=>new(x.Id,x.CustomerId,x.CustomerName,x.Name,x.Venue,x.StartsAt,x.EndsAt,x.Status,x.BudgetedRevenue,x.BudgetedCost,expenses.Sum(e=>(decimal?)e.Amount)??0,x.BudgetedRevenue-(expenses.Sum(e=>(decimal?)e.Amount)??0),x.Notes,expenses.OrderByDescending(e=>e.ExpenseDate).Select(e=>new EventExpenseDto(e.Id,e.Description,e.Category,e.Amount,e.ExpenseDate)).ToList());
}
