using LankaSaaS.Application;using LankaSaaS.Domain;using LankaSaaS.Infrastructure;using Microsoft.EntityFrameworkCore;
public static class EventStaffingEndpoints
{
 public static void Map(WebApplication app){app.MapGet("/api/staffing/team",async(AppDbContext db,CancellationToken ct)=>Results.Ok(await db.Users.Where(x=>x.IsActive).OrderBy(x=>x.FirstName).Select(x=>new StaffingUserDto(x.Id,x.FirstName+" "+x.LastName,x.Role)).ToListAsync(ct))).RequireAuthorization();var g=app.MapGroup("/api/events/{eventId:guid}/staffing").RequireAuthorization();g.MapGet("/",Get);g.MapPost("/",Assign).AddEndpointFilter<ValidationFilter>();g.MapPost("/{assignmentId:guid}/check-in",CheckIn).AddEndpointFilter<ValidationFilter>();g.MapPost("/{assignmentId:guid}/check-out",CheckOut).AddEndpointFilter<ValidationFilter>();g.MapPatch("/{assignmentId:guid}/cancel",Cancel);}
 static async Task<IResult> Get(Guid eventId,AppDbContext db,CancellationToken ct){var ev=await db.Events.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==eventId,ct);if(ev is null)return Results.NotFound();var rows=await db.EventStaffAssignments.Where(x=>x.EventId==eventId).OrderBy(x=>x.ShiftStartsAt).ToListAsync(ct);return Results.Ok(new EventStaffingDto(ev.Id,ev.Name,rows.Where(x=>x.Status!=StaffingStatuses.Cancelled).Sum(x=>PlannedHours(x)*x.HourlyRate),rows.Sum(x=>x.ActualCost),rows.Select(Dto).ToList()));}
 static async Task<IResult> Assign(Guid eventId,StaffAssignmentRequest r,AppDbContext db,ITenantContext tenant,CancellationToken ct){if(r.ShiftEndsAt<=r.ShiftStartsAt)return Results.BadRequest(new{message="Shift end must be after its start."});var ev=await db.Events.SingleOrDefaultAsync(x=>x.Id==eventId,ct);if(ev is null)return Results.NotFound();var user=await db.Users.SingleOrDefaultAsync(x=>x.Id==r.UserId&&x.IsActive,ct);if(user is null)return Results.BadRequest(new{message="Select an active team member."});var conflict=await db.EventStaffAssignments.AnyAsync(x=>x.UserId==r.UserId&&x.Status!=StaffingStatuses.Cancelled&&x.ShiftStartsAt<r.ShiftEndsAt&&r.ShiftStartsAt<x.ShiftEndsAt,ct);if(conflict)return Results.Conflict(new{message="This team member already has an overlapping shift."});var x=new EventStaffAssignment{TenantId=tenant.TenantId,EventId=eventId,UserId=user.Id,StaffName=user.FirstName+" "+user.LastName,Responsibility=r.Responsibility.Trim(),ShiftStartsAt=r.ShiftStartsAt,ShiftEndsAt=r.ShiftEndsAt,HourlyRate=r.HourlyRate,Notes=Clean(r.Notes)};db.EventStaffAssignments.Add(x);await db.SaveChangesAsync(ct);return Results.Created($"/api/events/{eventId}/staffing/{x.Id}",Dto(x));}
 static async Task<IResult> CheckIn(Guid eventId,Guid assignmentId,AttendanceRequest r,AppDbContext db,CancellationToken ct){var x=await db.EventStaffAssignments.SingleOrDefaultAsync(x=>x.Id==assignmentId&&x.EventId==eventId,ct);if(x is null)return Results.NotFound();if(x.Status!=StaffingStatuses.Scheduled)return Results.Conflict(new{message="Only scheduled staff can check in."});x.CheckedInAt=r.At;x.Status=StaffingStatuses.CheckedIn;await db.SaveChangesAsync(ct);return Results.NoContent();}
 static async Task<IResult> CheckOut(Guid eventId,Guid assignmentId,AttendanceRequest r,AppDbContext db,ITenantContext tenant,CancellationToken ct){var x=await db.EventStaffAssignments.SingleOrDefaultAsync(x=>x.Id==assignmentId&&x.EventId==eventId,ct);if(x is null)return Results.NotFound();if(x.Status!=StaffingStatuses.CheckedIn||x.CheckedInAt is null)return Results.Conflict(new{message="The team member must be checked in first."});if(r.At<=x.CheckedInAt)return Results.BadRequest(new{message="Check-out must be after check-in."});await using var tx=await db.Database.BeginTransactionAsync(ct);x.CheckedOutAt=r.At;x.ActualHours=Math.Round((decimal)(r.At-x.CheckedInAt.Value).TotalHours,2);x.ActualCost=Math.Round(x.ActualHours*x.HourlyRate,2);x.Status=StaffingStatuses.Completed;if(x.ActualCost>0){var date=BusinessClock.FromInstant(r.At);db.Expenses.Add(new Expense{TenantId=tenant.TenantId,EventId=eventId,EventStaffAssignmentId=x.Id,Description=$"Labour: {x.StaffName} — {x.Responsibility}",Category="Labour",Amount=x.ActualCost,ExpenseDate=date});await AccountingService.Post(db,tenant,date,$"Labour for {x.StaffName}","StaffAssignment",x.Id,eventId,null,[(SystemAccountCodes.EventExpenses,x.ActualCost,0),(SystemAccountCodes.Payables,0,x.ActualCost)],ct);}await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Results.Ok(Dto(x));}
 static async Task<IResult> Cancel(Guid eventId,Guid assignmentId,AppDbContext db,CancellationToken ct){var x=await db.EventStaffAssignments.SingleOrDefaultAsync(x=>x.Id==assignmentId&&x.EventId==eventId,ct);if(x is null)return Results.NotFound();if(x.Status!=StaffingStatuses.Scheduled)return Results.Conflict(new{message="Only a scheduled assignment can be cancelled."});x.Status=StaffingStatuses.Cancelled;await db.SaveChangesAsync(ct);return Results.NoContent();}
 static decimal PlannedHours(EventStaffAssignment x)=>Math.Round((decimal)(x.ShiftEndsAt-x.ShiftStartsAt).TotalHours,2);static StaffAssignmentDto Dto(EventStaffAssignment x)=>new(x.Id,x.EventId,x.UserId,x.StaffName,x.Responsibility,x.ShiftStartsAt,x.ShiftEndsAt,x.HourlyRate,PlannedHours(x),Math.Round(PlannedHours(x)*x.HourlyRate,2),x.Status,x.CheckedInAt,x.CheckedOutAt,x.ActualHours,x.ActualCost,x.Notes);static string? Clean(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
