using LankaSaaS.Application;using LankaSaaS.Domain;using LankaSaaS.Infrastructure;using Microsoft.EntityFrameworkCore;
public static class LogisticsEndpoints
{
 static readonly string[] Types=["Equipment","Vehicle","Consumable"];static readonly string[] ResourceStates=[ResourceStatuses.Available,ResourceStatuses.Maintenance,ResourceStatuses.Retired];
 public static void Map(WebApplication app){var r=app.MapGroup("/api/logistics/resources").RequireAuthorization();r.MapGet("/",async(AppDbContext db)=>Results.Ok(await db.LogisticsResources.OrderBy(x=>x.Name).Select(x=>new LogisticsResourceDto(x.Id,x.Name,x.Type,x.Identifier,x.TotalQuantity,x.Status,x.Notes)).ToListAsync()));r.MapPost("/",CreateResource).AddEndpointFilter<ValidationFilter>();var e=app.MapGroup("/api/events/{eventId:guid}/logistics").RequireAuthorization();e.MapGet("/",GetEventLogistics);e.MapPost("/allocations",Allocate).AddEndpointFilter<ValidationFilter>();e.MapPost("/allocations/{id:guid}/dispatch",Dispatch);e.MapPost("/allocations/{id:guid}/return",Return).AddEndpointFilter<ValidationFilter>();e.MapDelete("/allocations/{id:guid}",Cancel);e.MapPost("/checklist",AddChecklist).AddEndpointFilter<ValidationFilter>();e.MapPatch("/checklist/{id:guid}/toggle",ToggleChecklist);}
 static async Task<IResult> CreateResource(LogisticsResourceRequest r,AppDbContext db){if(!Types.Contains(r.Type)||!ResourceStates.Contains(r.Status))return Results.BadRequest(new{message="Select a valid resource type and status."});var x=new LogisticsResource{Name=r.Name.Trim(),Type=r.Type,Identifier=Clean(r.Identifier),TotalQuantity=r.TotalQuantity,Status=r.Status,Notes=Clean(r.Notes)};db.LogisticsResources.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/logistics/resources/{x.Id}",new LogisticsResourceDto(x.Id,x.Name,x.Type,x.Identifier,x.TotalQuantity,x.Status,x.Notes));}
 static async Task<IResult> GetEventLogistics(Guid eventId,AppDbContext db){if(!await db.Events.AnyAsync(x=>x.Id==eventId))return Results.NotFound();var allocations=await db.EventResourceAllocations.Where(x=>x.EventId==eventId).OrderBy(x=>x.ResourceName).Select(x=>new AllocationDto(x.Id,x.EventId,x.ResourceId,x.ResourceName,x.Quantity,x.Status,x.ReturnedQuantity,x.DamagedQuantity,x.MissingQuantity)).ToListAsync();var checklist=await db.EventChecklistItems.Where(x=>x.EventId==eventId).OrderBy(x=>x.CreatedAt).Select(x=>new ChecklistDto(x.Id,x.EventId,x.Description,x.IsCompleted,x.CompletedAt)).ToListAsync();return Results.Ok(new{allocations,checklist});}
 static async Task<IResult> Allocate(Guid eventId,AllocationRequest r,AppDbContext db,ITenantContext tenant){var ev=await db.Events.SingleOrDefaultAsync(x=>x.Id==eventId);var resource=await db.LogisticsResources.SingleOrDefaultAsync(x=>x.Id==r.ResourceId);if(ev is null||resource is null)return Results.NotFound();if(resource.Status!=ResourceStatuses.Available)return Results.Conflict(new{message="This resource is not available for allocation."});await using var tx=await db.Database.BeginTransactionAsync();await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtext({resource.Id.ToString()}))");var reserved=await (from a in db.EventResourceAllocations join other in db.Events on a.EventId equals other.Id where a.ResourceId==resource.Id&&a.Status!=AllocationStatuses.Cancelled&&a.Status!=AllocationStatuses.Returned&&other.Status!=EventStatuses.Cancelled&&other.StartsAt<ev.EndsAt&&other.EndsAt>ev.StartsAt select a.Quantity).SumAsync(x=>(int?)x)??0;if(reserved+r.Quantity>resource.TotalQuantity)return Results.Conflict(new{message=$"Only {Math.Max(0,resource.TotalQuantity-reserved)} units are available during this event."});var x=new EventResourceAllocation{TenantId=tenant.TenantId,EventId=eventId,ResourceId=resource.Id,ResourceName=resource.Name,Quantity=r.Quantity};db.EventResourceAllocations.Add(x);await db.SaveChangesAsync();await tx.CommitAsync();return Results.Created($"/api/events/{eventId}/logistics/allocations/{x.Id}",new AllocationDto(x.Id,eventId,resource.Id,resource.Name,r.Quantity,x.Status,0,0,0));}
 static async Task<IResult> Dispatch(Guid eventId,Guid id,AppDbContext db){var x=await db.EventResourceAllocations.SingleOrDefaultAsync(x=>x.Id==id&&x.EventId==eventId);if(x is null)return Results.NotFound();if(x.Status!=AllocationStatuses.Reserved)return Results.Conflict(new{message="Only reserved resources can be dispatched."});x.Status=AllocationStatuses.Dispatched;await db.SaveChangesAsync();return Results.NoContent();}
 static async Task<IResult> Return(Guid eventId,Guid id,ReturnAllocationRequest r,AppDbContext db){var x=await db.EventResourceAllocations.SingleOrDefaultAsync(x=>x.Id==id&&x.EventId==eventId);if(x is null)return Results.NotFound();if(x.Status!=AllocationStatuses.Dispatched)return Results.Conflict(new{message="Only dispatched resources can be returned."});if(r.ReturnedQuantity+r.DamagedQuantity+r.MissingQuantity!=x.Quantity)return Results.BadRequest(new{message="Returned, damaged and missing quantities must equal the dispatched quantity."});x.ReturnedQuantity=r.ReturnedQuantity;x.DamagedQuantity=r.DamagedQuantity;x.MissingQuantity=r.MissingQuantity;x.Status=AllocationStatuses.Returned;await db.SaveChangesAsync();return Results.NoContent();}
 static async Task<IResult> Cancel(Guid eventId,Guid id,AppDbContext db){var x=await db.EventResourceAllocations.SingleOrDefaultAsync(x=>x.Id==id&&x.EventId==eventId);if(x is null)return Results.NotFound();if(x.Status!=AllocationStatuses.Reserved)return Results.Conflict(new{message="Only reserved allocations can be cancelled."});x.Status=AllocationStatuses.Cancelled;await db.SaveChangesAsync();return Results.NoContent();}
 static async Task<IResult> AddChecklist(Guid eventId,ChecklistRequest r,AppDbContext db){if(!await db.Events.AnyAsync(x=>x.Id==eventId))return Results.NotFound();var x=new EventChecklistItem{EventId=eventId,Description=r.Description.Trim()};db.EventChecklistItems.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/events/{eventId}/logistics/checklist/{x.Id}",new ChecklistDto(x.Id,eventId,x.Description,false,null));}
 static async Task<IResult> ToggleChecklist(Guid eventId,Guid id,AppDbContext db,ITenantContext tenant){var x=await db.EventChecklistItems.SingleOrDefaultAsync(x=>x.Id==id&&x.EventId==eventId);if(x is null)return Results.NotFound();x.IsCompleted=!x.IsCompleted;x.CompletedAt=x.IsCompleted?DateTimeOffset.UtcNow:null;x.CompletedByUserId=x.IsCompleted?tenant.UserId:null;await db.SaveChangesAsync();return Results.NoContent();}
 static string? Clean(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
