using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.ComponentModel.DataAnnotations;
using LankaSaaS.Application;
using LankaSaaS.Domain;
using LankaSaaS.Infrastructure;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder=WebApplication.CreateBuilder(args);
var jwtKey=builder.Configuration["Jwt:Key"] ?? throw new InvalidOperationException("Jwt:Key is required");
builder.Services.AddHttpContextAccessor(); builder.Services.AddScoped<ITenantContext,HttpTenantContext>();
builder.Services.AddDbContext<AppDbContext>(o=>o.UseNpgsql(builder.Configuration.GetConnectionString("Default")));
builder.Services.AddScoped<IPasswordHasher<User>,PasswordHasher<User>>(); builder.Services.AddScoped<TokenService>();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>o.TokenValidationParameters=new(){ValidateIssuer=true,ValidateAudience=true,ValidateLifetime=true,ValidateIssuerSigningKey=true,ValidIssuer=builder.Configuration["Jwt:Issuer"],ValidAudience=builder.Configuration["Jwt:Audience"],IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),ClockSkew=TimeSpan.FromSeconds(30)});
builder.Services.AddAuthorization(o=>o.AddPolicy("AdminOnly",p=>p.RequireRole(Roles.Admin))); builder.Services.AddProblemDetails(); builder.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.WithOrigins(builder.Configuration["FrontendUrl"]??"http://localhost:3000").AllowAnyHeader().AllowAnyMethod()));
var app=builder.Build(); app.UseExceptionHandler(); app.UseCors(); app.UseAuthentication(); app.UseAuthorization();
if(app.Configuration.GetValue<bool>("Database:EnsureCreated")){using var scope=app.Services.CreateScope();await scope.ServiceProvider.GetRequiredService<AppDbContext>().Database.EnsureCreatedAsync();}

var auth=app.MapGroup("/api/auth").AddEndpointFilter<ValidationFilter>();
auth.MapPost("/register",async(RegisterRequest r,AppDbContext db,IPasswordHasher<User> hasher,TokenService tokens,CancellationToken ct)=>{
 var email=r.Email.Trim().ToLowerInvariant(); if(await db.Users.IgnoreQueryFilters().AnyAsync(x=>x.Email==email,ct)) return Results.Conflict(new{message="An account with this email already exists."});
 await using var tx=await db.Database.BeginTransactionAsync(ct); var tenant=new Tenant{Name=r.BusinessName.Trim(),BusinessName=r.BusinessName.Trim(),Email=email,Phone=r.Phone,Address=r.Address}; db.Tenants.Add(tenant);
 var user=new User{TenantId=tenant.Id,FirstName=r.FirstName.Trim(),LastName=r.LastName.Trim(),Email=email,PasswordHash="",Role=Roles.Admin}; user.PasswordHash=hasher.HashPassword(user,r.Password); db.Users.Add(user); var result=tokens.Create(user); db.RefreshTokens.Add(result.Stored); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return Results.Created("/api/auth/me",result.Response);
}).AllowAnonymous();
auth.MapPost("/login",async(LoginRequest r,AppDbContext db,IPasswordHasher<User> hasher,TokenService tokens,CancellationToken ct)=>{
 var user=await db.Users.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.Email==r.Email.Trim().ToLowerInvariant(),ct); if(user is null||!user.IsActive||hasher.VerifyHashedPassword(user,user.PasswordHash,r.Password)==PasswordVerificationResult.Failed) return Results.Unauthorized(); var result=tokens.Create(user); db.RefreshTokens.Add(result.Stored); await db.SaveChangesAsync(ct); return Results.Ok(result.Response);
}).AllowAnonymous();
auth.MapPost("/refresh",async(RefreshRequest r,AppDbContext db,TokenService tokens,CancellationToken ct)=>{
 var hash=TokenService.Hash(r.RefreshToken); var old=await db.RefreshTokens.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.TokenHash==hash,ct); if(old is null||old.RevokedAt!=null||old.ExpiresAt<=DateTimeOffset.UtcNow) return Results.Unauthorized(); var user=await db.Users.IgnoreQueryFilters().SingleAsync(x=>x.Id==old.UserId,ct); old.RevokedAt=DateTimeOffset.UtcNow; var next=tokens.Create(user); db.RefreshTokens.Add(next.Stored); await db.SaveChangesAsync(ct); return Results.Ok(next.Response);
}).AllowAnonymous();
auth.MapPost("/logout",async(RefreshRequest r,AppDbContext db,CancellationToken ct)=>{var hash=TokenService.Hash(r.RefreshToken); var token=await db.RefreshTokens.SingleOrDefaultAsync(x=>x.TokenHash==hash,ct); if(token is not null){token.RevokedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);} return Results.NoContent();}).RequireAuthorization();

MapCrud(app); InvoiceEndpoints.Map(app); app.MapGet("/health",()=>Results.Ok(new{status="healthy"})); app.Run();

static void MapCrud(WebApplication app){
 var c=app.MapGroup("/api/customers").RequireAuthorization(); c.MapGet("/",async(AppDbContext db)=>Results.Ok(await db.Customers.OrderByDescending(x=>x.CreatedAt).Select(x=>new CustomerDto(x.Id,x.Name,x.Phone,x.Email,x.Address,x.CreatedAt)).ToListAsync())); c.MapGet("/{id:guid}",async(Guid id,AppDbContext db)=>await db.Customers.Where(x=>x.Id==id).Select(x=>new CustomerDto(x.Id,x.Name,x.Phone,x.Email,x.Address,x.CreatedAt)).SingleOrDefaultAsync() is {} x?Results.Ok(x):Results.NotFound()); c.MapPost("/",async(CustomerRequest r,AppDbContext db)=>{var x=new Customer{Name=r.Name,Phone=r.Phone,Email=r.Email,Address=r.Address};db.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/customers/{x.Id}",new CustomerDto(x.Id,x.Name,x.Phone,x.Email,x.Address,x.CreatedAt));}); c.MapPut("/{id:guid}",async(Guid id,CustomerRequest r,AppDbContext db)=>{var x=await db.Customers.FindAsync(id);if(x is null)return Results.NotFound();x.Name=r.Name;x.Phone=r.Phone;x.Email=r.Email;x.Address=r.Address;await db.SaveChangesAsync();return Results.NoContent();}); c.MapDelete("/{id:guid}",async(Guid id,AppDbContext db)=>{var x=await db.Customers.FindAsync(id);if(x is null)return Results.NotFound();db.Remove(x);await db.SaveChangesAsync();return Results.NoContent();});
 var p=app.MapGroup("/api/products").RequireAuthorization(); p.MapGet("/",async(AppDbContext db)=>Results.Ok(await db.Products.OrderBy(x=>x.Name).Select(x=>new ProductDto(x.Id,x.Name,x.SKU,x.Description,x.SellingPrice,x.CostPrice,x.StockQuantity,x.IsActive,x.CreatedAt)).ToListAsync())); p.MapGet("/{id:guid}",async(Guid id,AppDbContext db)=>await db.Products.Where(x=>x.Id==id).Select(x=>new ProductDto(x.Id,x.Name,x.SKU,x.Description,x.SellingPrice,x.CostPrice,x.StockQuantity,x.IsActive,x.CreatedAt)).SingleOrDefaultAsync() is {} x?Results.Ok(x):Results.NotFound()); p.MapPost("/",async(ProductRequest r,AppDbContext db)=>{var x=new Product{Name=r.Name,SKU=r.SKU,Description=r.Description,SellingPrice=r.SellingPrice,CostPrice=r.CostPrice,StockQuantity=r.StockQuantity,IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/products/{x.Id}",new ProductDto(x.Id,x.Name,x.SKU,x.Description,x.SellingPrice,x.CostPrice,x.StockQuantity,x.IsActive,x.CreatedAt));}); p.MapPut("/{id:guid}",async(Guid id,ProductRequest r,AppDbContext db)=>{var x=await db.Products.FindAsync(id);if(x is null)return Results.NotFound();x.Name=r.Name;x.SKU=r.SKU;x.Description=r.Description;x.SellingPrice=r.SellingPrice;x.CostPrice=r.CostPrice;x.StockQuantity=r.StockQuantity;x.IsActive=r.IsActive;await db.SaveChangesAsync();return Results.NoContent();}); p.MapDelete("/{id:guid}",async(Guid id,AppDbContext db)=>{var x=await db.Products.FindAsync(id);if(x is null)return Results.NotFound();db.Remove(x);await db.SaveChangesAsync();return Results.NoContent();});
 var e=app.MapGroup("/api/expenses").RequireAuthorization(); e.MapGet("/",async(AppDbContext db)=>Results.Ok(await db.Expenses.OrderByDescending(x=>x.ExpenseDate).Select(x=>new ExpenseDto(x.Id,x.Description,x.Amount,x.ExpenseDate,x.Category,x.CreatedAt)).ToListAsync())); e.MapGet("/{id:guid}",async(Guid id,AppDbContext db)=>await db.Expenses.Where(x=>x.Id==id).Select(x=>new ExpenseDto(x.Id,x.Description,x.Amount,x.ExpenseDate,x.Category,x.CreatedAt)).SingleOrDefaultAsync() is {} x?Results.Ok(x):Results.NotFound()); e.MapPost("/",async(ExpenseRequest r,AppDbContext db)=>{var x=new Expense{Description=r.Description,Amount=r.Amount,ExpenseDate=r.ExpenseDate,Category=r.Category};db.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/expenses/{x.Id}",new ExpenseDto(x.Id,x.Description,x.Amount,x.ExpenseDate,x.Category,x.CreatedAt));}); e.MapPut("/{id:guid}",async(Guid id,ExpenseRequest r,AppDbContext db)=>{var x=await db.Expenses.FindAsync(id);if(x is null)return Results.NotFound();x.Description=r.Description;x.Amount=r.Amount;x.ExpenseDate=r.ExpenseDate;x.Category=r.Category;await db.SaveChangesAsync();return Results.NoContent();}); e.MapDelete("/{id:guid}",async(Guid id,AppDbContext db)=>{var x=await db.Expenses.FindAsync(id);if(x is null)return Results.NotFound();db.Remove(x);await db.SaveChangesAsync();return Results.NoContent();});
}

public sealed class HttpTenantContext(IHttpContextAccessor accessor):ITenantContext { public bool IsAuthenticated=>accessor.HttpContext?.User.Identity?.IsAuthenticated==true; public Guid TenantId=>Guid.Parse(accessor.HttpContext!.User.FindFirstValue("tenant_id")!); public Guid UserId=>Guid.Parse(accessor.HttpContext!.User.FindFirstValue(ClaimTypes.NameIdentifier)!); }
public sealed class TokenService(IConfiguration config){ public (AuthResponse Response,RefreshToken Stored) Create(User u){var now=DateTimeOffset.UtcNow;var exp=now.AddMinutes(config.GetValue("Jwt:AccessMinutes",15));var claims=new[]{new Claim(JwtRegisteredClaimNames.Sub,u.Id.ToString()),new Claim(ClaimTypes.NameIdentifier,u.Id.ToString()),new Claim("tenant_id",u.TenantId.ToString()),new Claim(ClaimTypes.Role,u.Role),new Claim(JwtRegisteredClaimNames.Email,u.Email)};var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:Key"]!));var jwt=new JwtSecurityToken(config["Jwt:Issuer"],config["Jwt:Audience"],claims,now.UtcDateTime,exp.UtcDateTime,new SigningCredentials(key,SecurityAlgorithms.HmacSha256));var raw=Convert.ToBase64String(RandomNumberGenerator.GetBytes(48));var stored=new RefreshToken{TenantId=u.TenantId,UserId=u.Id,TokenHash=Hash(raw),ExpiresAt=now.AddDays(config.GetValue("Jwt:RefreshDays",7))};return(new AuthResponse(new JwtSecurityTokenHandler().WriteToken(jwt),raw,exp,new UserDto(u.Id,u.FirstName,u.LastName,u.Email,u.Role)),stored);} public static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));}
public sealed class ValidationFilter:IEndpointFilter { public async ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext c,EndpointFilterDelegate next){var errors=new Dictionary<string,string[]>();foreach(var arg in c.Arguments.Where(x=>x is not null)){var results=new List<ValidationResult>();if(!Validator.TryValidateObject(arg!,new ValidationContext(arg!),results,true))foreach(var result in results)foreach(var member in result.MemberNames.DefaultIfEmpty("request"))errors[member]=[result.ErrorMessage??"Invalid value"];}return errors.Count>0?Results.ValidationProblem(errors):await next(c);}}
public partial class Program { }
