using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;namespace LankaSaaS.Infrastructure.Migrations;
[DbContext(typeof(AppDbContext))][Migration("202608120012_AccountingFoundation")]public sealed class AccountingFoundation:Migration
{
 protected override void Up(MigrationBuilder m)=>m.Sql("""
CREATE TABLE IF NOT EXISTS "LedgerAccounts" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"Code" text NOT NULL,"Name" text NOT NULL,"Type" text NOT NULL,"IsSystem" boolean NOT NULL,"IsActive" boolean NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS "IX_LedgerAccounts_TenantId_Code" ON "LedgerAccounts" ("TenantId","Code");
CREATE TABLE IF NOT EXISTS "JournalEntries" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"EntryDate" date NOT NULL,"Description" text NOT NULL,"Reference" text NULL,"EventId" uuid NULL,"SourceType" text NOT NULL,"SourceId" uuid NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS "IX_JournalEntries_TenantId_SourceType_SourceId" ON "JournalEntries" ("TenantId","SourceType","SourceId");CREATE INDEX IF NOT EXISTS "IX_JournalEntries_EventId" ON "JournalEntries" ("EventId");
CREATE TABLE IF NOT EXISTS "JournalLines" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"JournalEntryId" uuid NOT NULL,"AccountId" uuid NOT NULL,"AccountCode" text NOT NULL,"AccountName" text NOT NULL,"Debit" numeric(18,2) NOT NULL,"Credit" numeric(18,2) NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL,CONSTRAINT "FK_JournalLines_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries" ("Id") ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS "IX_JournalLines_JournalEntryId" ON "JournalLines" ("JournalEntryId");CREATE INDEX IF NOT EXISTS "IX_JournalLines_AccountId" ON "JournalLines" ("AccountId");
""");protected override void Down(MigrationBuilder m)=>m.Sql("""DROP TABLE IF EXISTS "JournalLines";DROP TABLE IF EXISTS "JournalEntries";DROP TABLE IF EXISTS "LedgerAccounts";""");
}
