using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;namespace LankaSaaS.Infrastructure.Migrations;
[DbContext(typeof(AppDbContext))][Migration("202608120011_EventFinance")]public sealed class EventFinance:Migration
{
protected override void Up(MigrationBuilder m)=>m.Sql("""
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "EventId" uuid NULL;ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "QuotationId" uuid NULL;CREATE INDEX IF NOT EXISTS "IX_Invoices_EventId" ON "Invoices" ("EventId");CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invoices_QuotationId" ON "Invoices" ("QuotationId") WHERE "QuotationId" IS NOT NULL;
CREATE TABLE IF NOT EXISTS "EventQuotations" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"EventId" uuid NOT NULL,"QuotationNumber" text NOT NULL,"Status" text NOT NULL,"IssueDate" date NOT NULL,"ValidUntil" date NOT NULL,"Total" numeric(18,2) NOT NULL,"DepositRequired" numeric(18,2) NOT NULL,"Notes" text NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS "IX_EventQuotations_QuotationNumber" ON "EventQuotations" ("QuotationNumber");CREATE INDEX IF NOT EXISTS "IX_EventQuotations_EventId" ON "EventQuotations" ("EventId");
CREATE TABLE IF NOT EXISTS "EventQuotationItems" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"EventQuotationId" uuid NOT NULL,"Description" text NOT NULL,"Quantity" numeric(18,2) NOT NULL,"UnitPrice" numeric(18,2) NOT NULL,"LineTotal" numeric(18,2) NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL,CONSTRAINT "FK_EventQuotationItems_EventQuotations_EventQuotationId" FOREIGN KEY ("EventQuotationId") REFERENCES "EventQuotations" ("Id") ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS "IX_EventQuotationItems_EventQuotationId" ON "EventQuotationItems" ("EventQuotationId");
CREATE TABLE IF NOT EXISTS "CustomerPayments" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"EventId" uuid NOT NULL,"InvoiceId" uuid NOT NULL,"Amount" numeric(18,2) NOT NULL,"PaymentDate" date NOT NULL,"Method" text NOT NULL,"Reference" text NULL,"IsDeposit" boolean NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);CREATE INDEX IF NOT EXISTS "IX_CustomerPayments_InvoiceId" ON "CustomerPayments" ("InvoiceId");CREATE INDEX IF NOT EXISTS "IX_CustomerPayments_EventId" ON "CustomerPayments" ("EventId");
""");protected override void Down(MigrationBuilder m)=>m.Sql("""DROP TABLE IF EXISTS "CustomerPayments";DROP TABLE IF EXISTS "EventQuotationItems";DROP TABLE IF EXISTS "EventQuotations";DROP INDEX IF EXISTS "IX_Invoices_QuotationId";DROP INDEX IF EXISTS "IX_Invoices_EventId";ALTER TABLE "Invoices" DROP COLUMN IF EXISTS "QuotationId";ALTER TABLE "Invoices" DROP COLUMN IF EXISTS "EventId";""");}
