using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;namespace LankaSaaS.Infrastructure.Migrations;
[DbContext(typeof(AppDbContext))][Migration("202608120010_Purchasing")]public sealed class Purchasing:Migration
{
protected override void Up(MigrationBuilder m)=>m.Sql("""
CREATE TABLE IF NOT EXISTS "Suppliers" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"Name" text NOT NULL,"ContactName" text NULL,"Phone" text NULL,"Email" text NULL,"Address" text NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);CREATE INDEX IF NOT EXISTS "IX_Suppliers_TenantId_Name" ON "Suppliers" ("TenantId","Name");
CREATE TABLE IF NOT EXISTS "PurchaseOrders" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"SupplierId" uuid NOT NULL,"SupplierName" text NOT NULL,"EventId" uuid NULL,"Type" text NOT NULL,"Status" text NOT NULL,"OrderDate" date NOT NULL,"RentalStartDate" date NULL,"RentalEndDate" date NULL,"Total" numeric(18,2) NOT NULL,"Notes" text NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS "PurchaseOrderItems" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"PurchaseOrderId" uuid NOT NULL,"ResourceId" uuid NULL,"Description" text NOT NULL,"Quantity" numeric(18,2) NOT NULL,"UnitCost" numeric(18,2) NOT NULL,"LineTotal" numeric(18,2) NOT NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL,CONSTRAINT "FK_PurchaseOrderItems_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS "IX_PurchaseOrderItems_PurchaseOrderId" ON "PurchaseOrderItems" ("PurchaseOrderId");
CREATE TABLE IF NOT EXISTS "SupplierPayments" ("Id" uuid PRIMARY KEY,"TenantId" uuid NOT NULL,"PurchaseOrderId" uuid NOT NULL,"Amount" numeric(18,2) NOT NULL,"PaymentDate" date NOT NULL,"Method" text NOT NULL,"Reference" text NULL,"CreatedAt" timestamptz NOT NULL,"UpdatedAt" timestamptz NOT NULL);CREATE INDEX IF NOT EXISTS "IX_SupplierPayments_PurchaseOrderId" ON "SupplierPayments" ("PurchaseOrderId");
ALTER TABLE "Expenses" ADD COLUMN IF NOT EXISTS "PurchaseOrderId" uuid NULL;CREATE UNIQUE INDEX IF NOT EXISTS "IX_Expenses_PurchaseOrderId" ON "Expenses" ("PurchaseOrderId") WHERE "PurchaseOrderId" IS NOT NULL;
""");protected override void Down(MigrationBuilder m)=>m.Sql("""DROP INDEX IF EXISTS "IX_Expenses_PurchaseOrderId";ALTER TABLE "Expenses" DROP COLUMN IF EXISTS "PurchaseOrderId";DROP TABLE IF EXISTS "SupplierPayments";DROP TABLE IF EXISTS "PurchaseOrderItems";DROP TABLE IF EXISTS "PurchaseOrders";DROP TABLE IF EXISTS "Suppliers";""");}
