'use client';
import Link from 'next/link';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {getPlatformSession,platformApi,setPlatformSession} from '@/lib/platform-api';

type Owner={id:string;email:string;role:string;isActive:boolean;lastLoginAt:string|null;createdAt:string};
type AccessChange={owner:Owner;isActive:boolean;reason:string};

export default function PlatformOwners(){
 const router=useRouter(),[owners,setOwners]=useState<Owner[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[loading,setLoading]=useState(true),[createOpen,setCreateOpen]=useState(false),[access,setAccess]=useState<AccessChange|null>(null),[passwordOpen,setPasswordOpen]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setOwners(await platformApi<Owner[]>('/owners'))}catch(x){setError((x as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!getPlatformSession()){router.replace('/platform/login');return}void load()},[load,router]);
 function logout(){setPlatformSession(null);router.replace('/platform/login')}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(event.currentTarget));await platformApi('/owners',{method:'POST',body:JSON.stringify(values)});setCreateOpen(false);setSuccess('Platform owner created successfully.');await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function changeAccess(event:FormEvent){event.preventDefault();if(!access)return;setBusy(true);setError('');try{await platformApi(`/owners/${access.owner.id}/access`,{method:'PUT',body:JSON.stringify({isActive:access.isActive,reason:access.reason})});const wasSelf=access.owner.email===getPlatformSession()?.email&&!access.isActive;setAccess(null);if(wasSelf){logout();return}setSuccess(`Platform owner ${access.isActive?'activated':'deactivated'} successfully.`);await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));if(values.newPassword!==values.confirmPassword){setError('New password and confirmation do not match.');setBusy(false);return}try{await platformApi('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:values.currentPassword,newPassword:values.newPassword})});setPlatformSession(null);router.replace('/platform/login')}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 return <div className="platform-shell"><header className="platform-top"><div><span className="platform-logo">LankaSaaS</span><span className="platform-console-label">Platform console</span></div><nav className="platform-nav"><Link href="/platform/tenants">Tenants</Link><Link className="active" href="/platform/owners">Owners</Link></nav><div className="platform-account"><span>{getPlatformSession()?.email}</span><button className="btn secondary compact" onClick={logout}>Sign out</button></div></header><main className="platform-content"><div className="heading"><div><p className="platform-eyebrow">Security administration</p><h1>Platform owners</h1><p className="muted">Manage the small group permitted to control tenant subscriptions.</p></div><div className="actions"><button className="btn secondary" onClick={()=>setPasswordOpen(true)}>Change my password</button><button className="btn" onClick={()=>setCreateOpen(true)}>Add owner</button></div></div>{error&&<div className="error" role="alert">{error}</div>}{success&&<div className="success" role="status">{success}</div>}<div className="platform-security-banner"><strong>Protected operator accounts</strong><span>Deactivation revokes existing sessions immediately. The final active owner cannot be deactivated.</span></div><div className="table-wrap"><table className="table platform-table"><thead><tr><th>Owner</th><th>Status</th><th>Last login</th><th>Created</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading owners...</td></tr>:owners.map(owner=><tr key={owner.id}><td><strong>{owner.email}</strong><small>{owner.role}</small></td><td><span className={`platform-status ${owner.isActive?'active':'suspended'}`}>{owner.isActive?'Active':'Inactive'}</span></td><td>{owner.lastLoginAt?new Date(owner.lastLoginAt).toLocaleString('en-LK'):'Never'}</td><td>{new Date(owner.createdAt).toLocaleDateString('en-LK')}</td><td><button className="btn secondary compact" onClick={()=>setAccess({owner,isActive:!owner.isActive,reason:''})}>{owner.isActive?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></main>
 {createOpen&&<div className="dialog"><section className="card platform-dialog" role="dialog" aria-modal="true" aria-labelledby="create-owner-title"><div className="dialog-heading"><div><p className="platform-eyebrow">New operator account</p><h2 id="create-owner-title">Add platform owner</h2></div><button className="icon-btn" aria-label="Close" onClick={()=>setCreateOpen(false)}>×</button></div><form onSubmit={create}><label>Email<input name="email" type="email" required autoComplete="off"/></label><label>Temporary password<input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><p className="muted">Share the password securely. Ask the new owner to change it after first login.</p><div className="actions"><button type="button" className="btn secondary" onClick={()=>setCreateOpen(false)}>Cancel</button><button className="btn" disabled={busy}>{busy?'Creating...':'Create owner'}</button></div></form></section></div>}
 {access&&<div className="dialog"><section className="card platform-dialog" role="dialog" aria-modal="true" aria-labelledby="access-title"><div className="dialog-heading"><div><p className="platform-eyebrow">Sensitive action</p><h2 id="access-title">{access.isActive?'Activate':'Deactivate'} owner</h2><p className="muted">{access.owner.email}</p></div><button className="icon-btn" aria-label="Close" onClick={()=>setAccess(null)}>×</button></div><form onSubmit={changeAccess}><div className="platform-warning"><strong>{access.isActive?'Restore platform access?':'Revoke platform access?'}</strong><p>{access.isActive?'The owner will be able to sign in and manage tenant subscriptions.':'All existing sessions for this owner will become invalid immediately.'}</p></div><label>Reason<textarea required minLength={5} maxLength={500} rows={3} value={access.reason} onChange={x=>setAccess({...access,reason:x.target.value})}/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setAccess(null)}>Cancel</button><button className="btn platform-danger-button" disabled={busy}>{busy?'Saving...':access.isActive?'Confirm activation':'Confirm deactivation'}</button></div></form></section></div>}
 {passwordOpen&&<div className="dialog"><section className="card platform-dialog" role="dialog" aria-modal="true" aria-labelledby="password-title"><div className="dialog-heading"><div><p className="platform-eyebrow">Account security</p><h2 id="password-title">Change my password</h2></div><button className="icon-btn" aria-label="Close" onClick={()=>setPasswordOpen(false)}>×</button></div><form onSubmit={changePassword}><label>Current password<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>New password<input name="newPassword" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><label>Confirm new password<input name="confirmPassword" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><p className="muted">After changing your password, all platform sessions will be revoked and you must sign in again.</p><div className="actions"><button type="button" className="btn secondary" onClick={()=>setPasswordOpen(false)}>Cancel</button><button className="btn" disabled={busy}>{busy?'Changing...':'Change password'}</button></div></form></section></div>}</div>
}
