'use client';
import {FormEvent,useEffect,useState} from 'react';
import {api,getSession} from '@/lib/api';

type Customer={id:string;name:string;phone?:string;email?:string;address?:string};

export default function Page(){
 const [admin,setAdmin]=useState(false),[customers,setCustomers]=useState<Customer[]>([]),[creating,setCreating]=useState(false),[editing,setEditing]=useState<Customer|null>(null),[deleting,setDeleting]=useState<Customer|null>(null),[success,setSuccess]=useState(''),[error,setError]=useState('');
 const notice=(text:string)=>{setError('');setSuccess(text)},failure=(x:unknown)=>{setSuccess('');setError((x as Error).message)};
 async function load(){try{setCustomers(await api<Customer[]>('/customers'))}catch(x){failure(x)}}
 useEffect(()=>{setAdmin(getSession()?.user.role==='Admin');void load()},[]);
 const values=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('/customers',{method:'POST',body:JSON.stringify(values(e.currentTarget))});setCreating(false);await load();notice('Customer added successfully.')}catch(x){failure(x)}}
 async function update(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;try{await api(`/customers/${editing.id}`,{method:'PUT',body:JSON.stringify(values(e.currentTarget))});setEditing(null);await load();notice('Customer updated successfully.')}catch(x){failure(x)}}
 async function remove(){if(!deleting)return;try{await api(`/customers/${deleting.id}`,{method:'DELETE'});setDeleting(null);await load();notice('Customer deleted successfully.')}catch(x){setDeleting(null);failure(x)}}
 const form=(customer?:Customer)=><><label>Name<input name="name" required maxLength={160} defaultValue={customer?.name}/></label><label>Phone<input name="phone" maxLength={40} defaultValue={customer?.phone}/></label><label>Email<input name="email" type="email" defaultValue={customer?.email}/></label><label>Address<textarea name="address" rows={3} maxLength={500} defaultValue={customer?.address}/></label></>;
 return <><div className="heading"><div><h1>Customers</h1><p className="muted">Manage event clients and billing contacts.</p></div>{admin&&<button className="btn" onClick={()=>setCreating(true)}>Add customer</button>}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Address</th>{admin&&<th>Actions</th>}</tr></thead><tbody>{customers.length?customers.map(customer=><tr key={customer.id}><td><strong>{customer.name}</strong></td><td>{customer.phone||'—'}</td><td>{customer.email||'—'}</td><td>{customer.address||'—'}</td>{admin&&<td><button className="link-button" onClick={()=>setEditing(customer)}>Edit</button><button className="danger-link" onClick={()=>setDeleting(customer)}>Delete</button></td>}</tr>):<tr><td colSpan={admin?5:4} className="muted">No customers yet.</td></tr>}</tbody></table></div>{creating&&<div className="dialog"><div className="card"><h2>Add customer</h2><form onSubmit={create}>{form()}<div className="actions"><button type="button" className="btn secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn">Add customer</button></div></form></div></div>}{editing&&<div className="dialog"><div className="card"><h2>Edit customer</h2><form onSubmit={update}>{form(editing)}<div className="actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn">Save changes</button></div></form></div></div>}{deleting&&<div className="dialog confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="customer-delete-title"><div className="card"><div className="warning-icon" aria-hidden="true">!</div><h2 id="customer-delete-title">Delete customer?</h2><p><strong>{deleting.name}</strong> will be permanently deleted. Customers with event or invoice history cannot be deleted.</p><div className="actions"><button className="btn secondary" autoFocus onClick={()=>setDeleting(null)}>Cancel</button><button className="btn danger" onClick={()=>void remove()}>Delete customer</button></div></div></div>}{success&&<div className="dialog success-dialog" role="dialog" aria-modal="true" aria-labelledby="customer-success-title"><div className="card"><div className="success-icon" aria-hidden="true">✓</div><h2 id="customer-success-title">Success</h2><p>{success}</p><button className="btn" autoFocus onClick={()=>setSuccess('')}>OK</button></div></div>}</>;
}
