param([string]$BaseUrl='http://localhost:8080')
$ErrorActionPreference='Stop'; function Assert($ok,$message){if(-not $ok){throw $message}}
try { Invoke-RestMethod "$BaseUrl/api/customers" | Out-Null; throw 'Unauthorized endpoint accepted request' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected 401' }
$stamp=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds(); $pass='SafePass!123'
function Register($n){Invoke-RestMethod "$BaseUrl/api/auth/register" -Method Post -ContentType application/json -SessionVariable session -Body (@{businessName="Tenant $n";email="tenant$n-$stamp@example.com";password=$pass;firstName='Test';lastName='Admin'}|ConvertTo-Json)}
$a=Register 'A'; $b=Register 'B'; Assert ($a.accessToken -and $b.accessToken) 'Registration failed'
$login=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -SessionVariable loginSession -Body (@{email="tenantA-$stamp@example.com";password=$pass}|ConvertTo-Json); Assert $login.accessToken 'Login failed'
$renewed=Invoke-RestMethod "$BaseUrl/api/auth/refresh" -Method Post -WebSession $loginSession; Assert $renewed.accessToken 'Cookie-based token refresh failed'
$ha=@{Authorization="Bearer $($a.accessToken)"};$hb=@{Authorization="Bearer $($b.accessToken)"}
$staffEmail="staff-$stamp@example.com";$staff=Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Test';lastName='Staff';email=$staffEmail;password=$pass;role='Staff'}|ConvertTo-Json);Assert ($staff.role -eq 'Staff') 'Staff creation failed'
$staffLogin=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -Body (@{email=$staffEmail;password=$pass}|ConvertTo-Json);$hs=@{Authorization="Bearer $($staffLogin.accessToken)"}
try { Invoke-RestMethod "$BaseUrl/api/users" -Headers $hs | Out-Null; throw 'Staff accessed Admin endpoint' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected Staff 403' }
try { Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $hs | Out-Null; throw 'Staff accessed login activity' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected login activity Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/subscription" -Headers $hs | Out-Null; throw 'Staff accessed subscription' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected subscription Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/subscription/cancel" -Method Post -Headers $hs | Out-Null; throw 'Staff cancelled subscription' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected cancellation Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/payments/payhere/notify" -Method Post -ContentType 'application/x-www-form-urlencoded' -Body 'merchant_id=invalid&order_id=invalid&payhere_amount=2500.00&payhere_currency=LKR&status_code=2&md5sig=invalid'|Out-Null;throw 'Invalid payment notification was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected invalid payment signature rejection' }
$subscriptionA=Invoke-RestMethod "$BaseUrl/api/subscription" -Headers $ha;Assert ($subscriptionA.plan -eq 'Trial') 'Trial plan was not assigned';Assert ($subscriptionA.userLimit -eq 3) 'Trial user limit is incorrect';Assert ($subscriptionA.activeUsers -eq 2) 'Active subscription usage is incorrect'
$accessA=Invoke-RestMethod "$BaseUrl/api/subscription/access" -Headers $ha;Assert (-not $accessA.isReadOnly) 'Valid trial was incorrectly made read-only'
$secondStaff=Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Second';lastName='Staff';email="staff2-$stamp@example.com";password=$pass;role='Staff'}|ConvertTo-Json);Assert $secondStaff.id 'Second Staff creation failed'
try { Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Over';lastName='Limit';email="staff3-$stamp@example.com";password=$pass;role='Staff'}|ConvertTo-Json)|Out-Null;throw 'User limit was not enforced' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected user-limit conflict' }
$activityA=Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $ha;Assert ($activityA.totalLogins -ge 2) 'Tenant A login totals were not recorded';Assert ($activityA.activeUsersLast30Days -ge 2) 'Tenant A active users were not recorded';Assert ($activityA.recentLogins.Count -ge 2) 'Recent login activity was not recorded'
$activityB=Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $hb;Assert ($activityB.totalLogins -eq 0) 'Tenant B can see Tenant A login totals';Assert (-not ($activityB.recentLogins.email -contains $staffEmail)) 'Tenant B can see Tenant A login events'
try { Invoke-RestMethod "$BaseUrl/api/settings" -Method Put -Headers $hs -ContentType application/json -Body (@{businessName='Blocked';email=$staffEmail;invoicePrefix='NO';defaultPaymentTermsDays=14;defaultTaxRate=0}|ConvertTo-Json)|Out-Null;throw 'Staff updated company settings' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected settings Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/users/$($staff.id)" -Method Put -Headers $hb -ContentType application/json -Body (@{firstName='Cross';lastName='Tenant';role='Staff';isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Cross-tenant user was updated' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe user 404' }
$tenantAUsers=Invoke-RestMethod "$BaseUrl/api/users" -Headers $ha;Assert ($tenantAUsers.Count -eq 3) 'Tenant A user list is incorrect'
$adminA=$tenantAUsers|Where-Object {$_.role -eq 'Admin'}
try { Invoke-RestMethod "$BaseUrl/api/users/$($adminA.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{firstName=$adminA.firstName;lastName=$adminA.lastName;role='Staff';isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Last Admin was demoted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected last Admin safeguard' }
$settings=Invoke-RestMethod "$BaseUrl/api/settings" -Method Put -Headers $ha -ContentType application/json -Body (@{businessName='Tenant A Branded';email="tenantA-$stamp@example.com";phone='0112345678';address='Colombo';taxRegistrationNumber='TAX-123';invoicePrefix='LKS';defaultPaymentTermsDays=30;defaultTaxRate=10;invoiceFooter='Thank you';paymentInstructions='Bank transfer'}|ConvertTo-Json);Assert ($settings.invoicePrefix -eq 'LKS') 'Company settings update failed'
$customer=Invoke-RestMethod "$BaseUrl/api/customers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Tenant A Customer'}|ConvertTo-Json); Assert $customer.id 'Customer creation failed'
$event=Invoke-RestMethod "$BaseUrl/api/events" -Method Post -Headers $ha -ContentType application/json -Body (@{customerId=$customer.id;name='Test Event';venue='Colombo';startsAt=(Get-Date).AddDays(2).ToUniversalTime().ToString('o');endsAt=(Get-Date).AddDays(2).AddHours(4).ToUniversalTime().ToString('o');status='Planning';budgetedRevenue=100000;budgetedCost=60000;notes='Smoke test'}|ConvertTo-Json);Assert $event.id 'Event creation failed'
$eventCost=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/expenses" -Method Post -Headers $ha -ContentType application/json -Body (@{description='Transport';category='Logistics';amount=10000;expenseDate=(Get-Date -Format yyyy-MM-dd)}|ConvertTo-Json);Assert $eventCost.id 'Event expense creation failed'
$quote=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations" -Method Post -Headers $ha -ContentType application/json -Body (@{issueDate=(Get-Date -Format yyyy-MM-dd);validUntil=(Get-Date).AddDays(14).ToString('yyyy-MM-dd');depositRequired=30000;notes='Event package';items=@(@{description='Complete event package';quantity=1;unitPrice=100000})}|ConvertTo-Json -Depth 5);Assert $quote 'Quotation creation failed'
$finance=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $ha;$createdQuote=$finance.quotations|Select-Object -First 1;Assert ($createdQuote.total -eq 100000) 'Quotation total is incorrect'
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)/status/Sent" -Method Patch -Headers $ha|Out-Null;Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)/status/Accepted" -Method Patch -Headers $ha|Out-Null
$converted=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)/convert" -Method Post -Headers $ha;$finance=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $ha;Assert ($finance.invoiced -eq 100000) 'Quotation was not converted to an event invoice'
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/invoices/$($converted.id)/payments" -Method Post -Headers $ha -ContentType application/json -Body (@{amount=30000;paymentDate=(Get-Date -Format yyyy-MM-dd);method='Bank transfer';reference='DEP-1';isDeposit=$true}|ConvertTo-Json)|Out-Null
$finance=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $ha;Assert ($finance.received -eq 30000 -and $finance.receivable -eq 70000 -and $finance.actualProfit -eq 20000) 'Event payment or profitability calculation is incorrect'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $hb|Out-Null;throw 'Cross-tenant event finance was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe finance 404' }
$shiftStart=(Get-Date).AddHours(-4).ToUniversalTime();$shiftEnd=(Get-Date).AddHours(2).ToUniversalTime();$assignment=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Method Post -Headers $ha -ContentType application/json -Body (@{userId=$staff.id;responsibility='Event coordinator';shiftStartsAt=$shiftStart.ToString('o');shiftEndsAt=$shiftEnd.ToString('o');hourlyRate=1000;notes='Smoke test'}|ConvertTo-Json);Assert ($assignment.plannedCost -eq 6000) 'Planned labour cost is incorrect'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Method Post -Headers $ha -ContentType application/json -Body (@{userId=$staff.id;responsibility='Conflicting shift';shiftStartsAt=$shiftStart.AddHours(1).ToString('o');shiftEndsAt=$shiftEnd.AddHours(1).ToString('o');hourlyRate=1000}|ConvertTo-Json)|Out-Null;throw 'Overlapping staff shift was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected staffing conflict' }
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-in" -Method Post -Headers $ha -ContentType application/json -Body (@{at=$shiftStart.ToString('o')}|ConvertTo-Json)|Out-Null;$completed=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-out" -Method Post -Headers $ha -ContentType application/json -Body (@{at=$shiftStart.AddHours(4).ToString('o')}|ConvertTo-Json);Assert ($completed.actualHours -eq 4 -and $completed.actualCost -eq 4000) 'Attendance labour cost is incorrect'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Headers $hb|Out-Null;throw 'Cross-tenant staffing was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe staffing 404' }
$resource=Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Chair';type='Equipment';identifier='CHAIR';totalQuantity=10;status='Available';notes='Test'}|ConvertTo-Json);Assert $resource.id 'Logistics resource creation failed'
$allocation=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/allocations" -Method Post -Headers $ha -ContentType application/json -Body (@{resourceId=$resource.id;quantity=6}|ConvertTo-Json);Assert $allocation.id 'Resource allocation failed'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/allocations" -Method Post -Headers $ha -ContentType application/json -Body (@{resourceId=$resource.id;quantity=5}|ConvertTo-Json)|Out-Null;throw 'Over-allocation was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected allocation conflict' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics" -Headers $hb|Out-Null;throw 'Cross-tenant logistics were exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe logistics 404' }
$supplier=Invoke-RestMethod "$BaseUrl/api/suppliers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Event Supplier';contactName='Test';phone='0711234567';email="supplier-$stamp@example.com";address='Colombo'}|ConvertTo-Json);Assert $supplier.id 'Supplier creation failed'
$purchase=Invoke-RestMethod "$BaseUrl/api/purchase-orders" -Method Post -Headers $ha -ContentType application/json -Body (@{supplierId=$supplier.id;eventId=$event.id;type='Rental';orderDate=(Get-Date -Format yyyy-MM-dd);rentalStartDate=(Get-Date -Format yyyy-MM-dd);rentalEndDate=(Get-Date).AddDays(2).ToString('yyyy-MM-dd');notes='Test rental';items=@(@{resourceId=$null;description='Sound rental';quantity=1;unitCost=5000})}|ConvertTo-Json -Depth 5);Assert ($purchase.total -eq 5000) 'Purchase order total is incorrect'
Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Ordered" -Method Patch -Headers $ha|Out-Null;Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Received" -Method Patch -Headers $ha|Out-Null
$tenantBOrders=Invoke-RestMethod "$BaseUrl/api/purchase-orders" -Headers $hb;Assert ($tenantBOrders.Count -eq 0) 'Tenant B can see Tenant A purchase orders'
$eventSeen=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)" -Headers $ha;Assert ($eventSeen.actualCost -eq 19000) 'Event actual cost is incorrect';Assert ($eventSeen.forecastProfit -eq 81000) 'Event forecast profit is incorrect'
$accounts=Invoke-RestMethod "$BaseUrl/api/accounting/accounts" -Headers $ha;Assert ($accounts.Count -eq 5) 'Default chart of accounts was not created';Assert (($accounts|Where-Object code -eq '1100').balance -eq 70000) 'Accounts receivable balance is incorrect';Assert (($accounts|Where-Object code -eq '2000').balance -eq 9000) 'Accounts payable balance is incorrect'
$eventProfit=Invoke-RestMethod "$BaseUrl/api/accounting/profit-loss?eventId=$($event.id)" -Headers $ha;Assert ($eventProfit.revenue -eq 100000 -and $eventProfit.expenses -eq 19000 -and $eventProfit.netProfit -eq 81000) "Event profit and loss is incorrect. Revenue=$($eventProfit.revenue), Expenses=$($eventProfit.expenses), Net=$($eventProfit.netProfit), Range=$($eventProfit.from)..$($eventProfit.to)"
$journals=Invoke-RestMethod "$BaseUrl/api/accounting/journals?eventId=$($event.id)" -Headers $ha;Assert ($journals.Count -ge 5) 'Automatic accounting journals were not created'
$tenantBAccounts=Invoke-RestMethod "$BaseUrl/api/accounting/accounts" -Headers $hb;Assert (-not ($tenantBAccounts.balance|Where-Object {$_ -ne 0})) 'Tenant B can see Tenant A account balances'
try { Invoke-RestMethod "$BaseUrl/api/accounting/profit-loss?eventId=$($event.id)" -Headers $hb|Out-Null;throw 'Cross-tenant event accounting was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe accounting 404' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)" -Headers $hb|Out-Null;throw 'Cross-tenant event was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe event 404' }
$product=Invoke-RestMethod "$BaseUrl/api/products" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Tea';sku="TEA-$stamp";sellingPrice=100;costPrice=80;stockQuantity=10;isActive=$true}|ConvertTo-Json); Assert $product.id 'Product creation failed'
$invoice=Invoke-RestMethod "$BaseUrl/api/invoices" -Method Post -Headers $ha -ContentType application/json -Body (@{customerId=$customer.id;issueDate=(Get-Date -Format yyyy-MM-dd);dueDate=(Get-Date -Format yyyy-MM-dd);items=@(@{productId=$product.id;description='Tea';quantity=2;unitPrice=100;discount=10;taxRate=10})}|ConvertTo-Json -Depth 5); Assert ($invoice.total -eq 209) 'Invoice total calculation failed'
Assert ($invoice.invoiceNumber -like 'LKS-*') 'Invoice prefix was not applied'
try { Invoke-RestMethod "$BaseUrl/api/invoices/$($invoice.id)" -Headers $hb | Out-Null; throw 'Cross-tenant invoice was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe invoice 404' }
try { Invoke-RestMethod "$BaseUrl/api/customers/$($customer.id)" -Headers $hb | Out-Null; throw 'Cross-tenant customer was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe 404' }
$seen=Invoke-RestMethod "$BaseUrl/api/customers" -Headers $hb; Assert ($seen.Count -eq 0) 'Tenant B can see tenant A data'; Write-Host 'All API smoke tests passed.' -ForegroundColor Green
