param([string]$BaseUrl='http://localhost:8080')
$ErrorActionPreference='Stop'; function Assert($ok,$message){if(-not $ok){throw $message}}
try { Invoke-RestMethod "$BaseUrl/api/customers" | Out-Null; throw 'Unauthorized endpoint accepted request' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected 401' }
$ready=Invoke-RestMethod "$BaseUrl/health/ready";Assert ($ready.status -eq 'ready') 'Database readiness failed'
$stamp=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds(); $pass='SafePass!123'
function Register($n){Invoke-RestMethod "$BaseUrl/api/auth/register" -Method Post -ContentType application/json -SessionVariable session -Body (@{businessName="Tenant $n";email="tenant$n-$stamp@example.com";password=$pass;firstName='Test';lastName='Admin'}|ConvertTo-Json)}
$a=Register 'A'; $b=Register 'B'; Assert ($a.accessToken -and $b.accessToken) 'Registration failed'
$login=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -SessionVariable loginSession -Body (@{email="tenantA-$stamp@example.com";password=$pass}|ConvertTo-Json); Assert $login.accessToken 'Login failed'
if(([Uri]$BaseUrl).Scheme -eq 'https'){$renewed=Invoke-RestMethod "$BaseUrl/api/auth/refresh" -Method Post -WebSession $loginSession;Assert $renewed.accessToken 'Cookie-based token refresh failed'}else{Write-Host 'Skipping secure-cookie refresh check on HTTP. Run against the Cloudflare HTTPS URL to verify refresh.' -ForegroundColor Yellow}
$ha=@{Authorization="Bearer $($a.accessToken)"};$hb=@{Authorization="Bearer $($b.accessToken)"}
$staffEmail="staff-$stamp@example.com";$staff=Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Test';lastName='Staff';email=$staffEmail;password=$pass;role='Staff'}|ConvertTo-Json);Assert ($staff.role -eq 'Staff') 'Staff creation failed'
$staffLogin=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -Body (@{email=$staffEmail;password=$pass}|ConvertTo-Json);$hs=@{Authorization="Bearer $($staffLogin.accessToken)"}
$departmentsA=Invoke-RestMethod "$BaseUrl/api/departments" -Headers $ha;$departmentsB=Invoke-RestMethod "$BaseUrl/api/departments" -Headers $hb;Assert ($departmentsA.Count -eq 7 -and $departmentsB.Count -eq 7) 'Default departments were not created';Assert (-not ($departmentsB.id|Where-Object {$departmentsA.id -contains $_})) 'Tenant B can see Tenant A departments'
$logisticsDepartment=$departmentsA|Where-Object {$_.code -eq 'LOGISTICS'};Assert ($logisticsDepartment.permissions.permissionCode -contains 'logistics.operate') 'Logistics permission template is missing'
$customDepartment=Invoke-RestMethod "$BaseUrl/api/departments" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Client Services';code="CLIENT_$stamp";isActive=$true;permissions=@(@{permissionCode='contacts.view';minimumAccessLevel='Viewer'})}|ConvertTo-Json -Depth 5);Assert ($customDepartment.code -eq "CLIENT_$stamp") 'Custom department was not created'
$customDepartment=Invoke-RestMethod "$BaseUrl/api/departments/$($customDepartment.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{name='Client Experience';code="CLIENT_$stamp";isActive=$true;permissions=@(@{permissionCode='contacts.view';minimumAccessLevel='Viewer'},@{permissionCode='contacts.manage';minimumAccessLevel='Manager'})}|ConvertTo-Json -Depth 5);Assert ($customDepartment.name -eq 'Client Experience' -and $customDepartment.permissions.Count -eq 2) 'Custom department was not updated'
$generalDepartment=$departmentsA|Where-Object {$_.code -eq 'GENERAL'}
Invoke-RestMethod "$BaseUrl/api/users/$($staff.id)/departments" -Method Put -Headers $ha -ContentType application/json -Body (@{departments=@(@{departmentId=$logisticsDepartment.id;accessLevel='Member';isPrimary=$true},@{departmentId=$generalDepartment.id;accessLevel='Viewer';isPrimary=$false})}|ConvertTo-Json -Depth 5)|Out-Null
try { Invoke-RestMethod "$BaseUrl/api/profile" -Headers $hs|Out-Null;throw 'Old token remained valid after department access changed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected immediate token revocation after department access changed' }
$staffLogin=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -Body (@{email=$staffEmail;password=$pass}|ConvertTo-Json);$hs=@{Authorization="Bearer $($staffLogin.accessToken)"}
$staffRecord=(Invoke-RestMethod "$BaseUrl/api/users" -Headers $ha)|Where-Object {$_.id -eq $staff.id};Assert ($staffRecord.departments.Count -eq 2 -and ($staffRecord.departments|Where-Object {$_.isPrimary}).departmentCode -eq 'LOGISTICS') 'Multiple department assignments were not saved correctly'
Invoke-RestMethod "$BaseUrl/api/departments/$($customDepartment.id)" -Method Delete -Headers $ha|Out-Null
$accessHistory=Invoke-RestMethod "$BaseUrl/api/departments/access-history" -Headers $ha;Assert ($accessHistory.Count -ge 4 -and @($accessHistory|Where-Object {$_.description -like '*department access*'}).Count -ge 1) 'Department access changes were not audited'
try { Invoke-RestMethod "$BaseUrl/api/departments/access-history" -Headers $hs|Out-Null;throw 'Staff accessed department audit history' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected department audit history Admin-only 403' }
$staffAccess=Invoke-RestMethod "$BaseUrl/api/departments/my-access" -Headers $hs;Assert ($staffAccess.permissions -contains 'logistics.view' -and $staffAccess.permissions -contains 'logistics.operate' -and -not ($staffAccess.permissions -contains 'logistics.manage')) 'Department access levels were not enforced'
$null=Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Headers $hs
try { Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Method Post -Headers $hs -ContentType application/json -Body (@{name='Blocked resource';type='Equipment';totalQuantity=1;status='Available'}|ConvertTo-Json)|Out-Null;throw 'Logistics member used logistics.manage' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected logistics.manage 403 for Member access' }
try { Invoke-RestMethod "$BaseUrl/api/accounting/accounts" -Headers $hs|Out-Null;throw 'Logistics member accessed accounting' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected accounting.view 403 for Logistics member' }
try { Invoke-RestMethod "$BaseUrl/api/users/$($staff.id)/departments" -Method Put -Headers $hb -ContentType application/json -Body (@{departments=@(@{departmentId=$departmentsB[0].id;accessLevel='Manager';isPrimary=$true})}|ConvertTo-Json -Depth 5)|Out-Null;throw 'Tenant B changed Tenant A department membership' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe department assignment 404' }
$staffPhoto='https://images.example.com/staff-profile.jpg';$profile=Invoke-RestMethod "$BaseUrl/api/profile" -Method Put -Headers $hs -ContentType application/json -Body (@{profilePhotoUrl=$staffPhoto}|ConvertTo-Json);Assert ($profile.id -eq $staff.id -and $profile.profilePhotoUrl -eq $staffPhoto) 'Employee profile photo update failed'
$adminProfile=Invoke-RestMethod "$BaseUrl/api/profile" -Headers $ha;Assert ($adminProfile.id -ne $staff.id -and [string]::IsNullOrWhiteSpace([string]$adminProfile.profilePhotoUrl)) 'Employee changed another user profile'
$tenantBProfile=Invoke-RestMethod "$BaseUrl/api/profile" -Headers $hb;Assert ($tenantBProfile.id -ne $staff.id -and [string]::IsNullOrWhiteSpace([string]$tenantBProfile.profilePhotoUrl)) 'Tenant B can see Tenant A profile data'
try { Invoke-RestMethod "$BaseUrl/api/profile" -Method Put -Headers $hs -ContentType application/json -Body (@{profilePhotoUrl='http://insecure.example.com/photo.jpg'}|ConvertTo-Json)|Out-Null;throw 'Insecure profile photo URL was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 400) 'Expected insecure profile URL rejection' }
try { Invoke-RestMethod "$BaseUrl/api/users" -Headers $hs | Out-Null; throw 'Staff accessed Admin endpoint' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected Staff 403' }
try { Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $hs | Out-Null; throw 'Staff accessed login activity' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected login activity Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/subscription" -Headers $hs | Out-Null; throw 'Staff accessed subscription' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected subscription Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/subscription/cancel" -Method Post -Headers $hs | Out-Null; throw 'Staff cancelled subscription' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected cancellation Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/payments/payhere/notify" -Method Post -ContentType 'application/x-www-form-urlencoded' -Body 'merchant_id=invalid&order_id=invalid&payhere_amount=2500.00&payhere_currency=LKR&status_code=2&md5sig=invalid'|Out-Null;throw 'Invalid payment notification was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected invalid payment signature rejection' }
$subscriptionA=Invoke-RestMethod "$BaseUrl/api/subscription" -Headers $ha;Assert ($subscriptionA.plan -eq 'Trial') 'Trial plan was not assigned';Assert ($subscriptionA.userLimit -eq 3) 'Trial user limit is incorrect';Assert ($subscriptionA.activeUsers -eq 2) 'Active subscription usage is incorrect'
$accessA=Invoke-RestMethod "$BaseUrl/api/subscription/access" -Headers $ha;Assert (-not $accessA.isReadOnly) 'Valid trial was incorrectly made read-only'
$secondStaff=Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Second';lastName='Staff';email="staff2-$stamp@example.com";password=$pass;role='Staff'}|ConvertTo-Json);Assert $secondStaff.id 'Second Staff creation failed'
try { Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Over';lastName='Limit';email="staff3-$stamp@example.com";password=$pass;role='Staff'}|ConvertTo-Json)|Out-Null;throw 'User limit was not enforced' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected user-limit conflict' }
$activityA=Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $ha;Assert ($activityA.totalLogins -ge 2) 'Tenant A login totals were not recorded';Assert ($activityA.activeUsersLast30Days -ge 2) 'Tenant A active users were not recorded';Assert ($activityA.recentLogins.Count -ge 2) 'Recent login activity was not recorded'
$activityB=Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $hb;Assert ($activityB.totalLogins -eq 0) 'Tenant B can see Tenant A login totals';Assert (-not ($activityB.recentLogins.email -contains $staffEmail)) 'Tenant B can see Tenant A login events'
try { Invoke-RestMethod "$BaseUrl/api/settings" -Method Put -Headers $hs -ContentType application/json -Body (@{businessName='Blocked';email=$staffEmail;invoicePrefix='NO';defaultPaymentTermsDays=14;defaultTaxRate=0}|ConvertTo-Json)|Out-Null;throw 'Staff updated company settings' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected settings Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/users/$($staff.id)" -Method Put -Headers $hb -ContentType application/json -Body (@{firstName='Cross';lastName='Tenant';role='Staff';isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Cross-tenant user was updated' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe user 404' }
$tenantAUsers=Invoke-RestMethod "$BaseUrl/api/users" -Headers $ha;Assert ($tenantAUsers.Count -eq 3) 'Tenant A user list is incorrect'
$adminA=$tenantAUsers|Where-Object {$_.role -eq 'Admin'}
try { Invoke-RestMethod "$BaseUrl/api/users/$($adminA.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{firstName=$adminA.firstName;lastName=$adminA.lastName;role='Staff';isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Last Admin was demoted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected last Admin safeguard' }
$logoUrl='https://images.example.com/tenant-a-logo.png';$settings=Invoke-RestMethod "$BaseUrl/api/settings" -Method Put -Headers $ha -ContentType application/json -Body (@{businessName='Tenant A Branded';email="tenantA-$stamp@example.com";phone='0112345678';address='Colombo';taxRegistrationNumber='TAX-123';invoicePrefix='LKS';defaultPaymentTermsDays=30;defaultTaxRate=10;invoiceFooter='Thank you';paymentInstructions='Bank transfer';logoUrl=$logoUrl}|ConvertTo-Json);Assert ($settings.invoicePrefix -eq 'LKS' -and $settings.logoUrl -eq $logoUrl) 'Company settings or tenant branding update failed'
$customer=Invoke-RestMethod "$BaseUrl/api/customers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Tenant A Customer'}|ConvertTo-Json); Assert $customer.id 'Customer creation failed'
$editedCustomer=Invoke-RestMethod "$BaseUrl/api/customers/$($customer.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{name='Tenant A Customer Updated';phone='0112345678';email="customer-$stamp@example.com";address='Colombo'}|ConvertTo-Json);Assert ($editedCustomer.name -eq 'Tenant A Customer Updated') 'Customer update failed'
try { Invoke-RestMethod "$BaseUrl/api/customers" -Method Post -Headers $hs -ContentType application/json -Body (@{name='Blocked Customer'}|ConvertTo-Json)|Out-Null;throw 'Staff created a customer' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected customer Admin-only 403' }
$temporaryCustomer=Invoke-RestMethod "$BaseUrl/api/customers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Temporary Customer'}|ConvertTo-Json);Invoke-RestMethod "$BaseUrl/api/customers/$($temporaryCustomer.id)" -Method Delete -Headers $ha|Out-Null;Assert (-not ((Invoke-RestMethod "$BaseUrl/api/customers" -Headers $ha).id -contains $temporaryCustomer.id)) 'Unused customer deletion failed'
$event=Invoke-RestMethod "$BaseUrl/api/events" -Method Post -Headers $ha -ContentType application/json -Body (@{customerId=$customer.id;name='Test Event';venue='Colombo';startsAt=(Get-Date).AddHours(-1).ToUniversalTime().ToString('o');endsAt=(Get-Date).AddHours(5).ToUniversalTime().ToString('o');status='Planning';budgetedRevenue=100000;budgetedCost=60000;notes='Smoke test';requireLocationForAttendance=$true;latitude=6.9271;longitude=79.8612;attendanceRadiusMeters=150;maximumLocationAccuracyMeters=50;checkInWindowMinutes=60}|ConvertTo-Json);Assert ($event.id -and $event.requireLocationForAttendance) 'Geofenced event creation failed'
$eventUpdate=@{customerId=$customer.id;name='Test Event Updated';venue='Colombo';startsAt=$event.startsAt;endsAt=$event.endsAt;status='Confirmed';budgetedRevenue=100000;budgetedCost=60000;notes='Updated';requireLocationForAttendance=$true;latitude=6.9271;longitude=79.8612;attendanceRadiusMeters=150;maximumLocationAccuracyMeters=50;checkInWindowMinutes=60};$event=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)" -Method Put -Headers $ha -ContentType application/json -Body ($eventUpdate|ConvertTo-Json);Assert ($event.name -eq 'Test Event Updated' -and $event.status -eq 'Confirmed') 'Event update failed'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)" -Method Put -Headers $hs -ContentType application/json -Body ($eventUpdate|ConvertTo-Json)|Out-Null;throw 'Staff updated an event' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected event update Admin-only 403' }
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/status/Planning" -Method Patch -Headers $ha|Out-Null;$event=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/status/Confirmed" -Method Patch -Headers $ha;Assert ($event.status -eq 'Confirmed') 'Direct event status workflow failed'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/status/Completed" -Method Patch -Headers $ha|Out-Null;throw 'Invalid event status jump was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected invalid event status conflict' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/status/Planning" -Method Patch -Headers $hs|Out-Null;throw 'Staff changed event status' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected event status Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/customers/$($customer.id)" -Method Delete -Headers $ha|Out-Null;throw 'Customer with event history was deleted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected customer-history delete conflict' }
$eventCost=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/expenses" -Method Post -Headers $ha -ContentType application/json -Body (@{description='Transport';category='Logistics';amount=10000;expenseDate=(Get-Date -Format yyyy-MM-dd)}|ConvertTo-Json);Assert $eventCost.id 'Event expense creation failed'
$eventCost=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/expenses/$($eventCost.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{description='Event transport';category='Logistics';amount=10000;expenseDate=(Get-Date -Format yyyy-MM-dd)}|ConvertTo-Json);Assert ($eventCost.description -eq 'Event transport' -and -not $eventCost.isGenerated) 'Event expense update failed'
$temporaryEventCost=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/expenses" -Method Post -Headers $ha -ContentType application/json -Body (@{description='Temporary cost';category='Testing';amount=1;expenseDate=(Get-Date -Format yyyy-MM-dd)}|ConvertTo-Json);Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/expenses/$($temporaryEventCost.id)" -Method Delete -Headers $ha|Out-Null
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/expenses" -Method Post -Headers $hs -ContentType application/json -Body (@{description='Blocked';category='Testing';amount=1;expenseDate=(Get-Date -Format yyyy-MM-dd)}|ConvertTo-Json)|Out-Null;throw 'Staff created an event expense' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected event expense Admin-only 403' }
$quote=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations" -Method Post -Headers $ha -ContentType application/json -Body (@{issueDate=(Get-Date -Format yyyy-MM-dd);validUntil=(Get-Date).AddDays(14).ToString('yyyy-MM-dd');depositRequired=30000;notes='Event package';items=@(@{description='Complete event package';quantity=1;unitPrice=100000})}|ConvertTo-Json -Depth 5);Assert $quote 'Quotation creation failed'
$finance=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $ha;$createdQuote=$finance.quotations|Select-Object -First 1;Assert ($createdQuote.total -eq 100000) 'Quotation total is incorrect'
$createdQuote=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{issueDate=(Get-Date -Format yyyy-MM-dd);validUntil=(Get-Date).AddDays(21).ToString('yyyy-MM-dd');depositRequired=30000;notes='Updated event package';items=@(@{description='Updated complete event package';quantity=1;unitPrice=100000})}|ConvertTo-Json -Depth 5);Assert ($createdQuote.status -eq 'Draft' -and $createdQuote.items[0].description -eq 'Updated complete event package') 'Draft quotation update failed'
$temporaryQuote=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations" -Method Post -Headers $ha -ContentType application/json -Body (@{issueDate=(Get-Date -Format yyyy-MM-dd);validUntil=(Get-Date).AddDays(7).ToString('yyyy-MM-dd');depositRequired=0;items=@(@{description='Temporary quote';quantity=1;unitPrice=1})}|ConvertTo-Json -Depth 5);Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$temporaryQuote" -Method Delete -Headers $ha|Out-Null
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)/status/Sent" -Method Patch -Headers $ha|Out-Null;Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)/status/Accepted" -Method Patch -Headers $ha|Out-Null
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)" -Method Delete -Headers $ha|Out-Null;throw 'Sent quotation was deleted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected non-draft quotation delete conflict' }
$converted=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/quotations/$($createdQuote.id)/convert" -Method Post -Headers $ha;$finance=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $ha;Assert ($finance.invoiced -eq 100000) 'Quotation was not converted to an event invoice'
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance/invoices/$($converted.id)/payments" -Method Post -Headers $ha -ContentType application/json -Body (@{amount=30000;paymentDate=(Get-Date -Format yyyy-MM-dd);method='Bank transfer';reference='DEP-1';isDeposit=$true}|ConvertTo-Json)|Out-Null
$finance=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $ha;Assert ($finance.received -eq 30000 -and $finance.receivable -eq 70000 -and $finance.actualProfit -eq 20000) 'Event payment or profitability calculation is incorrect'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/finance" -Headers $hb|Out-Null;throw 'Cross-tenant event finance was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe finance 404' }
$shiftStart=(Get-Date).AddMinutes(-30).ToUniversalTime();$shiftEnd=(Get-Date).AddHours(3.5).ToUniversalTime();$assignment=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Method Post -Headers $ha -ContentType application/json -Body (@{userId=$staff.id;responsibility='Event coordinator';shiftStartsAt=$shiftStart.ToString('o');shiftEndsAt=$shiftEnd.ToString('o');hourlyRate=1000;notes='Smoke test'}|ConvertTo-Json);Assert ($assignment.plannedCost -eq 4000) 'Planned labour cost is incorrect'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Method Post -Headers $ha -ContentType application/json -Body (@{userId=$staff.id;responsibility='Conflicting shift';shiftStartsAt=$shiftStart.AddHours(1).ToString('o');shiftEndsAt=$shiftEnd.AddHours(1).ToString('o');hourlyRate=1000}|ConvertTo-Json)|Out-Null;throw 'Overlapping staff shift was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected staffing conflict' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-in" -Method Post -Headers $ha -ContentType application/json -Body (@{}|ConvertTo-Json)|Out-Null;throw 'Admin checked in another employee without an override' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected employee-only attendance 403' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-in" -Method Post -Headers $hs -ContentType application/json -Body (@{latitude=6.9271;longitude=79.8612;accuracyMeters=80}|ConvertTo-Json)|Out-Null;throw 'Inaccurate location was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 422) 'Expected inaccurate-location 422' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-in" -Method Post -Headers $hs -ContentType application/json -Body (@{latitude=6.95;longitude=79.90;accuracyMeters=10}|ConvertTo-Json)|Out-Null;throw 'Out-of-geofence location was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected out-of-geofence 403' }
$checkedIn=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-in" -Method Post -Headers $hs -ContentType application/json -Body (@{latitude=6.9271;longitude=79.8612;accuracyMeters=10}|ConvertTo-Json);Assert ($checkedIn.status -eq 'CheckedIn') 'Valid on-site check-in failed'
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/attendance-attempts" -Headers $hs|Out-Null;throw 'Staff accessed attendance audit' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected attendance audit Admin-only 403' }
$completed=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($assignment.id)/check-out" -Method Post -Headers $hs -ContentType application/json -Body (@{latitude=6.9271;longitude=79.8612;accuracyMeters=10}|ConvertTo-Json);Assert ($completed.status -eq 'Completed' -and $completed.actualHours -ge 0) 'Valid on-site check-out failed';$labourCost=$completed.actualCost
$overrideAssignment=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Method Post -Headers $ha -ContentType application/json -Body (@{userId=$secondStaff.id;responsibility='Setup support';shiftStartsAt=$shiftStart.ToString('o');shiftEndsAt=$shiftEnd.ToString('o');hourlyRate=500;notes='Override test'}|ConvertTo-Json)
$overridden=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/$($overrideAssignment.id)/check-in" -Method Post -Headers $ha -ContentType application/json -Body (@{isOverride=$true;overrideReason='Supervisor verified employee on site'}|ConvertTo-Json);Assert ($overridden.status -eq 'CheckedIn') 'Supervisor attendance override failed'
$attemptResponse=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/attendance-attempts" -Headers $ha;$attempts=@(foreach($attempt in $attemptResponse){$attempt});$rejected=@($attempts|Where-Object { -not [System.Convert]::ToBoolean($_.isAccepted) });$accepted=@($attempts|Where-Object { [System.Convert]::ToBoolean($_.isAccepted) });$overrides=@($attempts|Where-Object { [System.Convert]::ToBoolean($_.isOverride) -and -not [string]::IsNullOrWhiteSpace([string]$_.overrideReason) });$attemptSummary=$attempts|Select-Object action,isAccepted,isOverride,overrideReason|ConvertTo-Json -Compress;Assert ($rejected.Count -ge 2) "Rejected attendance attempts were not audited. Found=$($rejected.Count); Attempts=$attemptSummary";Assert ($accepted.Count -eq 3) "Accepted attendance attempts were not audited. Found=$($accepted.Count); Attempts=$attemptSummary";Assert ($overrides.Count -eq 1) "Supervisor override reason was not audited. Found=$($overrides.Count); Attempts=$attemptSummary"
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing" -Headers $hb|Out-Null;throw 'Cross-tenant staffing was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe staffing 404' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/staffing/attendance-attempts" -Headers $hb|Out-Null;throw 'Cross-tenant attendance audit was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe attendance audit 404' }
$resource=Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Chair';type='Equipment';identifier='CHAIR';totalQuantity=10;status='Available';notes='Test'}|ConvertTo-Json);Assert $resource.id 'Logistics resource creation failed'
$editedResource=Invoke-RestMethod "$BaseUrl/api/logistics/resources/$($resource.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{name='Banquet Chair';type='Equipment';identifier='CHAIR';totalQuantity=10;status='Available';notes='Updated'}|ConvertTo-Json);Assert ($editedResource.name -eq 'Banquet Chair') 'Logistics resource update failed'
try { Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Method Post -Headers $hs -ContentType application/json -Body (@{name='Blocked';type='Equipment';totalQuantity=1;status='Available'}|ConvertTo-Json)|Out-Null;throw 'Staff created a logistics resource' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected logistics resource Admin-only 403' }
$deletable=Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Temporary Resource';type='Equipment';totalQuantity=1;status='Available'}|ConvertTo-Json);Invoke-RestMethod "$BaseUrl/api/logistics/resources/$($deletable.id)" -Method Delete -Headers $ha|Out-Null;Assert (-not ((Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Headers $ha).id -contains $deletable.id)) 'Unused logistics resource deletion failed'
$allocation=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/allocations" -Method Post -Headers $ha -ContentType application/json -Body (@{resourceId=$resource.id;quantity=6}|ConvertTo-Json);Assert $allocation.id 'Resource allocation failed'
$checklistItem=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/checklist" -Method Post -Headers $ha -ContentType application/json -Body (@{description='Confirm equipment'}|ConvertTo-Json);Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/checklist/$($checklistItem.id)/toggle" -Method Patch -Headers $ha|Out-Null;$logisticsAfterToggle=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics" -Headers $ha;Assert (($logisticsAfterToggle.checklist|Where-Object id -eq $checklistItem.id).isCompleted) 'Checklist toggle failed'
try { Invoke-RestMethod "$BaseUrl/api/logistics/resources/$($resource.id)" -Method Delete -Headers $ha|Out-Null;throw 'Allocated resource was deleted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected allocated-resource delete conflict' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/allocations" -Method Post -Headers $ha -ContentType application/json -Body (@{resourceId=$resource.id;quantity=5}|ConvertTo-Json)|Out-Null;throw 'Over-allocation was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected allocation conflict' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics" -Headers $hb|Out-Null;throw 'Cross-tenant logistics were exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe logistics 404' }
$supplier=Invoke-RestMethod "$BaseUrl/api/suppliers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Event Supplier';contactName='Test';phone='0711234567';email="supplier-$stamp@example.com";address='Colombo'}|ConvertTo-Json);Assert $supplier.id 'Supplier creation failed'
$editedSupplier=Invoke-RestMethod "$BaseUrl/api/suppliers/$($supplier.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{name='Event Supplier Updated';contactName='Test';phone='0711234567';email="supplier-$stamp@example.com";address='Colombo'}|ConvertTo-Json);Assert ($editedSupplier.name -eq 'Event Supplier Updated') 'Supplier update failed'
try { Invoke-RestMethod "$BaseUrl/api/suppliers" -Method Post -Headers $hs -ContentType application/json -Body (@{name='Blocked Supplier'}|ConvertTo-Json)|Out-Null;throw 'Staff created a supplier' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected supplier Admin-only 403' }
$temporarySupplier=Invoke-RestMethod "$BaseUrl/api/suppliers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Temporary Supplier'}|ConvertTo-Json);Invoke-RestMethod "$BaseUrl/api/suppliers/$($temporarySupplier.id)" -Method Delete -Headers $ha|Out-Null;Assert (-not ((Invoke-RestMethod "$BaseUrl/api/suppliers" -Headers $ha).id -contains $temporarySupplier.id)) 'Unused supplier deletion failed'
$purchase=Invoke-RestMethod "$BaseUrl/api/purchase-orders" -Method Post -Headers $ha -ContentType application/json -Body (@{supplierId=$supplier.id;eventId=$event.id;type='Rental';orderDate=(Get-Date -Format yyyy-MM-dd);rentalStartDate=(Get-Date -Format yyyy-MM-dd);rentalEndDate=(Get-Date).AddDays(2).ToString('yyyy-MM-dd');notes='Test rental';items=@(@{resourceId=$null;description='Sound rental';quantity=1;unitCost=5000})}|ConvertTo-Json -Depth 5);Assert ($purchase.total -eq 5000) 'Purchase order total is incorrect'
try { Invoke-RestMethod "$BaseUrl/api/suppliers/$($supplier.id)" -Method Delete -Headers $ha|Out-Null;throw 'Supplier with order history was deleted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected supplier-history delete conflict' }
Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Ordered" -Method Patch -Headers $ha|Out-Null
Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Draft" -Method Patch -Headers $ha|Out-Null
Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Ordered" -Method Patch -Headers $ha|Out-Null
Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Received" -Method Patch -Headers $ha|Out-Null
try { Invoke-RestMethod "$BaseUrl/api/purchase-orders/$($purchase.id)/status/Draft" -Method Patch -Headers $ha|Out-Null;throw 'Received order was revised' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected received-order revision conflict' }
$tenantBOrders=Invoke-RestMethod "$BaseUrl/api/purchase-orders" -Headers $hb;Assert ($tenantBOrders.Count -eq 0) 'Tenant B can see Tenant A purchase orders'
$expectedEventCost=15000+$labourCost;$eventSeen=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)" -Headers $ha;Assert ($eventSeen.actualCost -eq $expectedEventCost) 'Event actual cost is incorrect';Assert ($eventSeen.forecastProfit -eq (100000-$expectedEventCost)) 'Event forecast profit is incorrect'
$accounts=Invoke-RestMethod "$BaseUrl/api/accounting/accounts" -Headers $ha;Assert ($accounts.Count -eq 5) 'Default chart of accounts was not created';Assert (($accounts|Where-Object code -eq '1100').balance -eq 70000) 'Accounts receivable balance is incorrect';Assert (($accounts|Where-Object code -eq '2000').balance -eq (5000+$labourCost)) 'Accounts payable balance is incorrect'
$eventProfit=Invoke-RestMethod "$BaseUrl/api/accounting/profit-loss?eventId=$($event.id)" -Headers $ha;Assert ($eventProfit.revenue -eq 100000 -and $eventProfit.expenses -eq $expectedEventCost -and $eventProfit.netProfit -eq (100000-$expectedEventCost)) "Event profit and loss is incorrect. Revenue=$($eventProfit.revenue), Expenses=$($eventProfit.expenses), Net=$($eventProfit.netProfit), Range=$($eventProfit.from)..$($eventProfit.to)"
$journals=Invoke-RestMethod "$BaseUrl/api/accounting/journals?eventId=$($event.id)" -Headers $ha;$expectedJournalCount=if($labourCost -gt 0){5}else{4};Assert ($journals.Count -ge $expectedJournalCount) "Automatic accounting journals were not created. Expected=$expectedJournalCount, Found=$($journals.Count), LabourCost=$labourCost"
$reportHealth=Invoke-RestMethod "$BaseUrl/api/reports/events/health" -Headers $ha;Assert ($reportHealth.module -eq 'event-reporting') 'The running API image does not contain event reporting'
$report=Invoke-RestMethod "$BaseUrl/api/reports/events" -Headers $ha;Assert ($report.eventCount -eq 1) "Event reporting count is incorrect. Count=$($report.eventCount), Range=$($report.from)..$($report.to)";Assert ($report.invoicedRevenue -eq 100000 -and $report.actualCost -eq $expectedEventCost -and $report.profit -eq (100000-$expectedEventCost)) 'Event reporting financial totals are incorrect';Assert ($report.receivables -eq 70000 -and $report.payables -eq (5000+$labourCost)) 'Event reporting customer receivable or supplier payable is incorrect';Assert ($report.quotationConversionPercent -eq 100 -and $report.logisticsUtilizationPercent -eq 60) 'Event reporting operational ratios are incorrect';Assert ($report.actualLabourCost -eq $labourCost) 'Event reporting labour total is incorrect'
$singleEventReport=Invoke-RestMethod "$BaseUrl/api/reports/events?eventId=$($event.id)" -Headers $ha;Assert ($singleEventReport.eventCount -eq 1 -and $singleEventReport.events[0].eventId -eq $event.id) 'Selected-event report filter failed'
try { Invoke-RestMethod "$BaseUrl/api/reports/events?eventId=$($event.id)" -Headers $hb|Out-Null;throw 'Cross-tenant selected-event report was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe selected-event report 404' }
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/allocations/$($allocation.id)/dispatch" -Method Post -Headers $ha|Out-Null
Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics/allocations/$($allocation.id)/return" -Method Post -Headers $ha -ContentType application/json -Body (@{returnedQuantity=6;damagedQuantity=1;missingQuantity=0}|ConvertTo-Json)|Out-Null
$returnedLogistics=Invoke-RestMethod "$BaseUrl/api/events/$($event.id)/logistics" -Headers $ha;$returnedAllocation=$returnedLogistics.allocations|Where-Object id -eq $allocation.id;Assert ($returnedAllocation.status -eq 'Returned' -and $returnedAllocation.returnedQuantity -eq 6 -and $returnedAllocation.damagedQuantity -eq 1) 'Damaged resource return was not recorded correctly'
$resourceAfterReturn=@(Invoke-RestMethod "$BaseUrl/api/logistics/resources" -Headers $ha)|Where-Object {$_.id -eq $resource.id};Assert ($resourceAfterReturn.Count -eq 1 -and $resourceAfterReturn[0].totalQuantity -eq 9) "Damaged resource was not removed from available stock. Expected=9, Found=$($resourceAfterReturn[0].totalQuantity), Matches=$($resourceAfterReturn.Count)"
$export=Invoke-RestMethod "$BaseUrl/api/reports/events/export" -Headers $ha;Assert ($export.fileName -like 'event-report-*.csv' -and $export.content -like '*Test Event*') 'Event CSV export is incorrect'
$tenantBReport=Invoke-RestMethod "$BaseUrl/api/reports/events" -Headers $hb;Assert ($tenantBReport.eventCount -eq 0 -and $tenantBReport.invoicedRevenue -eq 0) 'Tenant B can see Tenant A event reporting'
$audit=Invoke-RestMethod "$BaseUrl/api/audit?take=500" -Headers $ha;Assert ($audit.Count -gt 0) 'Authenticated mutations were not audited';Assert (-not ($audit|Where-Object {$_.correlationId.Length -lt 10})) 'Audit correlation ID is missing'
try { Invoke-RestMethod "$BaseUrl/api/audit" -Headers $hs|Out-Null;throw 'Staff accessed audit log' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected audit Admin-only 403' }
$tenantBAudit=Invoke-RestMethod "$BaseUrl/api/audit" -Headers $hb;Assert (-not ($tenantBAudit|Where-Object {$_.path -like '*events*'})) 'Tenant B can see Tenant A audit events'
$tenantBAccounts=Invoke-RestMethod "$BaseUrl/api/accounting/accounts" -Headers $hb;Assert (-not ($tenantBAccounts.balance|Where-Object {$_ -ne 0})) 'Tenant B can see Tenant A account balances'
try { Invoke-RestMethod "$BaseUrl/api/accounting/profit-loss?eventId=$($event.id)" -Headers $hb|Out-Null;throw 'Cross-tenant event accounting was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe accounting 404' }
try { Invoke-RestMethod "$BaseUrl/api/events/$($event.id)" -Headers $hb|Out-Null;throw 'Cross-tenant event was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe event 404' }
$product=Invoke-RestMethod "$BaseUrl/api/products" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Tea';sku="TEA-$stamp";sellingPrice=100;costPrice=80;stockQuantity=10;isActive=$true}|ConvertTo-Json); Assert $product.id 'Product creation failed'
$editedProduct=Invoke-RestMethod "$BaseUrl/api/products/$($product.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{name='Ceylon Tea';sku="TEA-$stamp";sellingPrice=110;costPrice=80;stockQuantity=10;isActive=$true}|ConvertTo-Json);Assert ($editedProduct.name -eq 'Ceylon Tea' -and $editedProduct.sellingPrice -eq 110) 'Product update failed'
try { Invoke-RestMethod "$BaseUrl/api/products" -Method Post -Headers $hs -ContentType application/json -Body (@{name='Blocked';sku="BLOCK-$stamp";sellingPrice=1;costPrice=1;stockQuantity=1;isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Staff created a product' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected product Admin-only 403' }
$temporaryProduct=Invoke-RestMethod "$BaseUrl/api/products" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Temporary Product';sku="TEMP-$stamp";sellingPrice=1;costPrice=1;stockQuantity=1;isActive=$true}|ConvertTo-Json);Invoke-RestMethod "$BaseUrl/api/products/$($temporaryProduct.id)" -Method Delete -Headers $ha|Out-Null;Assert (-not ((Invoke-RestMethod "$BaseUrl/api/products" -Headers $ha).id -contains $temporaryProduct.id)) 'Unused product deletion failed'
$invoice=Invoke-RestMethod "$BaseUrl/api/invoices" -Method Post -Headers $ha -ContentType application/json -Body (@{customerId=$customer.id;issueDate=(Get-Date -Format yyyy-MM-dd);dueDate=(Get-Date -Format yyyy-MM-dd);items=@(@{productId=$product.id;description='Tea';quantity=2;unitPrice=100;discount=10;taxRate=10})}|ConvertTo-Json -Depth 5); Assert ($invoice.total -eq 209) 'Invoice total calculation failed'
try { Invoke-RestMethod "$BaseUrl/api/products/$($product.id)" -Method Delete -Headers $ha|Out-Null;throw 'Invoiced product was deleted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected invoiced-product delete conflict' }
Assert ($invoice.invoiceNumber -like 'LKS-*') 'Invoice prefix was not applied'
try { Invoke-RestMethod "$BaseUrl/api/invoices/$($invoice.id)" -Headers $hb | Out-Null; throw 'Cross-tenant invoice was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe invoice 404' }
try { Invoke-RestMethod "$BaseUrl/api/customers/$($customer.id)" -Headers $hb | Out-Null; throw 'Cross-tenant customer was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe 404' }
$seen=Invoke-RestMethod "$BaseUrl/api/customers" -Headers $hb; Assert ($seen.Count -eq 0) 'Tenant B can see tenant A data'; Write-Host 'All API smoke tests passed.' -ForegroundColor Green
