param([string]$BaseUrl='http://localhost:8080')
$ErrorActionPreference='Stop'; function Assert($ok,$message){if(-not $ok){throw $message}}
try { Invoke-RestMethod "$BaseUrl/api/customers" | Out-Null; throw 'Unauthorized endpoint accepted request' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected 401' }
$stamp=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds(); $pass='SafePass!123'
function Register($n){Invoke-RestMethod "$BaseUrl/api/auth/register" -Method Post -ContentType application/json -SessionVariable session -Body (@{businessName="Tenant $n";email="tenant$n-$stamp@example.com";password=$pass;firstName='Test';lastName='Admin'}|ConvertTo-Json)}
$a=Register 'A'; $b=Register 'B'; Assert ($a.accessToken -and $b.accessToken) 'Registration failed'
$login=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -SessionVariable loginSession -Body (@{email="tenantA-$stamp@example.com";password=$pass}|ConvertTo-Json); Assert $login.accessToken 'Login failed'
$renewed=Invoke-RestMethod "$BaseUrl/api/auth/refresh" -Method Post -WebSession $loginSession; Assert $renewed.accessToken 'Cookie-based token refresh failed'
$ha=@{Authorization="Bearer $($a.accessToken)"};$hb=@{Authorization="Bearer $($b.accessToken)"}
$staffEmail="staff-$stamp@example.com";$staff=Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Test';lastName='Staff';email=$staffEmail;password=$pass;role='Staff'}|ConvertTo-Json);Assert ($staff.role -eq 'Staff') 'Staff creation failed'
$staffLogin=Invoke-RestMethod "$BaseUrl/api/auth/login" -Method Post -ContentType application/json -Body (@{email=$staffEmail;password=$pass}|ConvertTo-Json);$hs=@{Authorization="Bearer $($staffLogin.accessToken)"}
try { Invoke-RestMethod "$BaseUrl/api/users" -Headers $hs | Out-Null; throw 'Staff accessed Admin endpoint' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected Staff 403' }
try { Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $hs | Out-Null; throw 'Staff accessed login activity' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected login activity Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/subscription" -Headers $hs | Out-Null; throw 'Staff accessed subscription' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected subscription Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/subscription/cancel" -Method Post -Headers $hs | Out-Null; throw 'Staff cancelled subscription' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected cancellation Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/payments/payhere/notify" -Method Post -ContentType 'application/x-www-form-urlencoded' -Body 'merchant_id=invalid&order_id=invalid&payhere_amount=2500.00&payhere_currency=LKR&status_code=2&md5sig=invalid'|Out-Null;throw 'Invalid payment notification was accepted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 401) 'Expected invalid payment signature rejection' }
$subscriptionA=Invoke-RestMethod "$BaseUrl/api/subscription" -Headers $ha;Assert ($subscriptionA.plan -eq 'Trial') 'Trial plan was not assigned';Assert ($subscriptionA.userLimit -eq 3) 'Trial user limit is incorrect';Assert ($subscriptionA.activeUsers -eq 2) 'Active subscription usage is incorrect'
$secondStaff=Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Second';lastName='Staff';email="staff2-$stamp@example.com";password=$pass;role='Staff'}|ConvertTo-Json);Assert $secondStaff.id 'Second Staff creation failed'
try { Invoke-RestMethod "$BaseUrl/api/users" -Method Post -Headers $ha -ContentType application/json -Body (@{firstName='Over';lastName='Limit';email="staff3-$stamp@example.com";password=$pass;role='Staff'}|ConvertTo-Json)|Out-Null;throw 'User limit was not enforced' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected user-limit conflict' }
$activityA=Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $ha;Assert ($activityA.totalLogins -ge 2) 'Tenant A login totals were not recorded';Assert ($activityA.activeUsersLast30Days -ge 2) 'Tenant A active users were not recorded';Assert ($activityA.recentLogins.Count -ge 2) 'Recent login activity was not recorded'
$activityB=Invoke-RestMethod "$BaseUrl/api/login-activity" -Headers $hb;Assert ($activityB.totalLogins -eq 0) 'Tenant B can see Tenant A login totals';Assert (-not ($activityB.recentLogins.email -contains $staffEmail)) 'Tenant B can see Tenant A login events'
try { Invoke-RestMethod "$BaseUrl/api/settings" -Method Put -Headers $hs -ContentType application/json -Body (@{businessName='Blocked';email=$staffEmail;invoicePrefix='NO';defaultPaymentTermsDays=14;defaultTaxRate=0}|ConvertTo-Json)|Out-Null;throw 'Staff updated company settings' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 403) 'Expected settings Admin-only 403' }
try { Invoke-RestMethod "$BaseUrl/api/users/$($staff.id)" -Method Put -Headers $hb -ContentType application/json -Body (@{firstName='Cross';lastName='Tenant';role='Staff';isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Cross-tenant user was updated' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe user 404' }
$tenantAUsers=Invoke-RestMethod "$BaseUrl/api/users" -Headers $ha;Assert ($tenantAUsers.Count -eq 3) 'Tenant A user list is incorrect'
$adminA=$tenantAUsers|Where-Object {$_.role -eq 'Admin'}
try { Invoke-RestMethod "$BaseUrl/api/users/$($adminA.id)" -Method Put -Headers $ha -ContentType application/json -Body (@{firstName=$adminA.firstName;lastName=$adminA.lastName;role='Staff';isActive=$true}|ConvertTo-Json)|Out-Null;throw 'Last Admin was demoted' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 409) 'Expected last Admin safeguard' }
$settings=Invoke-RestMethod "$BaseUrl/api/settings" -Method Put -Headers $ha -ContentType application/json -Body (@{businessName='Tenant A Branded';email="tenantA-$stamp@example.com";phone='0112345678';address='Colombo';taxRegistrationNumber='TAX-123';invoicePrefix='LKS';defaultPaymentTermsDays=30;defaultTaxRate=10;invoiceFooter='Thank you';paymentInstructions='Bank transfer'}|ConvertTo-Json);Assert ($settings.invoicePrefix -eq 'LKS') 'Company settings update failed'
$customer=Invoke-RestMethod "$BaseUrl/api/customers" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Tenant A Customer'}|ConvertTo-Json); Assert $customer.id 'Customer creation failed'
$product=Invoke-RestMethod "$BaseUrl/api/products" -Method Post -Headers $ha -ContentType application/json -Body (@{name='Tea';sku="TEA-$stamp";sellingPrice=100;costPrice=80;stockQuantity=10;isActive=$true}|ConvertTo-Json); Assert $product.id 'Product creation failed'
$invoice=Invoke-RestMethod "$BaseUrl/api/invoices" -Method Post -Headers $ha -ContentType application/json -Body (@{customerId=$customer.id;issueDate=(Get-Date -Format yyyy-MM-dd);dueDate=(Get-Date -Format yyyy-MM-dd);items=@(@{productId=$product.id;description='Tea';quantity=2;unitPrice=100;discount=10;taxRate=10})}|ConvertTo-Json -Depth 5); Assert ($invoice.total -eq 209) 'Invoice total calculation failed'
Assert ($invoice.invoiceNumber -like 'LKS-*') 'Invoice prefix was not applied'
try { Invoke-RestMethod "$BaseUrl/api/invoices/$($invoice.id)" -Headers $hb | Out-Null; throw 'Cross-tenant invoice was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe invoice 404' }
try { Invoke-RestMethod "$BaseUrl/api/customers/$($customer.id)" -Headers $hb | Out-Null; throw 'Cross-tenant customer was exposed' } catch { Assert ($_.Exception.Response.StatusCode.value__ -eq 404) 'Expected tenant-safe 404' }
$seen=Invoke-RestMethod "$BaseUrl/api/customers" -Headers $hb; Assert ($seen.Count -eq 0) 'Tenant B can see tenant A data'; Write-Host 'All API smoke tests passed.' -ForegroundColor Green
