'use client';
import {FormEvent,useEffect,useState} from 'react';
import {api,getSession} from '@/lib/api';

type Product={id:string;name:string;sku:string;description?:string;sellingPrice:number;costPrice:number;stockQuantity:number;isActive:boolean};
const money=(value:number)=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR'}).format(value);

export default function Page(){
 const [admin,setAdmin]=useState(false),[products,setProducts]=useState<Product[]>([]),[creating,setCreating]=useState(false),[editing,setEditing]=useState<Product|null>(null),[deleting,setDeleting]=useState<Product|null>(null),[success,setSuccess]=useState(''),[error,setError]=useState('');
 const notice=(text:string)=>{setError('');setSuccess(text)},failure=(x:unknown)=>{setSuccess('');setError((x as Error).message)};
 async function load(){try{setProducts(await api<Product[]>('/products'))}catch(x){failure(x)}}
 useEffect(()=>{setAdmin(getSession()?.user.role==='Admin');void load()},[]);
 function values(form:HTMLFormElement){const f=Object.fromEntries(new FormData(form));return{name:f.name,sku:f.sku,description:f.description||null,sellingPrice:Number(f.sellingPrice),costPrice:Number(f.costPrice),stockQuantity:Number(f.stockQuantity),isActive:f.isActive==='on'}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('/products',{method:'POST',body:JSON.stringify(values(e.currentTarget))});setCreating(false);await load();notice('Product added successfully.')}catch(x){failure(x)}}
 async function update(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;try{await api(`/products/${editing.id}`,{method:'PUT',body:JSON.stringify(values(e.currentTarget))});setEditing(null);await load();notice('Product updated successfully.')}catch(x){failure(x)}}
 async function remove(){if(!deleting)return;try{await api(`/products/${deleting.id}`,{method:'DELETE'});setDeleting(null);await load();notice('Product deleted successfully.')}catch(x){setDeleting(null);failure(x)}}
 const form=(product?:Product)=><><label>Name<input name="name" required maxLength={160} defaultValue={product?.name}/></label><label>SKU<input name="sku" required maxLength={80} defaultValue={product?.sku}/></label><label>Description<textarea name="description" rows={3} defaultValue={product?.description}/></label><label>Selling price (LKR)<input name="sellingPrice" type="number" min="0" step="0.01" required defaultValue={product?.sellingPrice}/></label><label>Cost price (LKR)<input name="costPrice" type="number" min="0" step="0.01" required defaultValue={product?.costPrice}/></label><label>Stock quantity<input name="stockQuantity" type="number" min="0" step="1" required defaultValue={product?.stockQuantity}/></label><label className="check"><input name="isActive" type="checkbox" defaultChecked={product?.isActive??true}/> Active product</label></>;
 return <><div className="heading"><div><h1>Products</h1><p className="muted">Manage products, prices and stock.</p></div>{admin&&<button className="btn" onClick={()=>setCreating(true)}>Add product</button>}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>SKU</th><th>Selling price</th><th>Cost price</th><th>Stock</th><th>Status</th>{admin&&<th>Actions</th>}</tr></thead><tbody>{products.length?products.map(product=><tr key={product.id}><td><strong>{product.name}</strong></td><td>{product.sku}</td><td>{money(product.sellingPrice)}</td><td>{money(product.costPrice)}</td><td>{product.stockQuantity}</td><td><span className={`badge ${product.isActive?'success':''}`}>{product.isActive?'Active':'Inactive'}</span></td>{admin&&<td><button className="link-button" onClick={()=>setEditing(product)}>Edit</button><button className="danger-link" onClick={()=>setDeleting(product)}>Delete</button></td>}</tr>):<tr><td colSpan={admin?7:6} className="muted">No products yet.</td></tr>}</tbody></table></div>{creating&&<div className="dialog"><div className="card"><h2>Add product</h2><form onSubmit={create}>{form()}<div className="actions"><button type="button" className="btn secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn">Add product</button></div></form></div></div>}{editing&&<div className="dialog"><div className="card"><h2>Edit product</h2><form onSubmit={update}>{form(editing)}<div className="actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn">Save changes</button></div></form></div></div>}{deleting&&<div className="dialog confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="product-delete-title"><div className="card"><div className="warning-icon" aria-hidden="true">!</div><h2 id="product-delete-title">Delete product?</h2><p><strong>{deleting.name}</strong> will be permanently deleted. Products used on invoices cannot be deleted and should be marked inactive.</p><div className="actions"><button className="btn secondary" autoFocus onClick={()=>setDeleting(null)}>Cancel</button><button className="btn danger" onClick={()=>void remove()}>Delete product</button></div></div></div>}{success&&<div className="dialog success-dialog" role="dialog" aria-modal="true" aria-labelledby="product-success-title"><div className="card"><div className="success-icon" aria-hidden="true">✓</div><h2 id="product-success-title">Success</h2><p>{success}</p><button className="btn" autoFocus onClick={()=>setSuccess('')}>OK</button></div></div>}</>;
}
