'use client';
import Link from 'next/link';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {getPlatformSession,platformApi,setPlatformSession} from '@/lib/platform-api';

type Tenant={id:string;businessName:string;email:string;status:string;isTestTenant:boolean;isArchived:boolean;archivedAt:string|null;archivedReason:string|null};

export default function TenantCleanup(){
 const router=useRouter(),[tenants,setTenants]=useState<Tenant[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[selected,setSelected]=useState<Tenant|null>(null),[reason,setReason]=useState(''),[bulkOpen,setBulkOpen]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(()=>platformApi<Tenant[]>('/tenants').then(setTenants).catch(x=>setError((x as Error).message)),[]);
 useEffect(()=>{if(!getPlatformSession()){router.replace('/platform/login');return}void load()},[load,router]);
 function logout(){setPlatformSession(null);router.replace('/platform/login')}
 async function changeArchive(event:FormEvent){event.preventDefault();if(!selected)return;setBusy(true);setError('');try{await platformApi(`/tenants/${selected.id}/archive`,{method:'PUT',body:JSON.stringify({isArchived:!selected.isArchived,reason})});setSuccess(`${selected.businessName} ${selected.isArchived?'restored':'archived'} successfully.`);setSelected(null);setReason('');await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function bulkArchive(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=await platformApi<{archivedCount:number}>('/test-tenants/archive',{method:'POST',body:JSON.stringify({confirmation,reason})});setSuccess(result.archivedCount?`Archived ${result.archivedCount} explicitly marked test tenants.`:'No unarchived marked test tenants were found.');setBulkOpen(false);setConfirmation('');setReason('');await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 const marked=tenants.filter(x=>x.isTestTenant&&!x.isArchived),archived=tenants.filter(x=>x.isArchived);
 return <div className="platform-shell"><header className="platform-top"><div><span className="platform-logo">WebWaves Digital</span><span className="platform-console-label">Platform console</span></div><nav className="platform-nav"><Link href="/platform/tenants">Tenants</Link><Link href="/platform/owners">Owners</Link></nav><div className="platform-account"><span>{getPlatformSession()?.email}</span><button className="btn secondary compact" onClick={logout}>Sign out</button></div></header><main className="platform-content"><div className="heading"><div><p className="platform-eyebrow">Recoverable data control</p><h1>Tenant archival</h1><p className="muted">Archive tenant access without deleting business records. Archived tenants can be restored.</p></div><button className="btn" onClick={()=>{setBulkOpen(true);setReason('')}} disabled={!marked.length}>Archive marked test tenants</button></div>{error&&<div className="error">{error}</div>}{success&&<div className="success">{success}</div>}<div className="platform-security-banner"><strong>{marked.length} marked test tenants ready</strong><span>Only registrations explicitly marked by automated tests are eligible for the bulk action. Legacy records are never guessed from their names.</span></div><div className="table-wrap"><table className="table platform-table"><thead><tr><th>Company</th><th>Type</th><th>State</th><th>Archived reason</th><th></th></tr></thead><tbody>{tenants.map(x=><tr key={x.id}><td><strong>{x.businessName}</strong><small>{x.email}</small></td><td>{x.isTestTenant?'Marked test':'Regular tenant'}</td><td><span className={`platform-status ${x.isArchived?'archived':'active'}`}>{x.isArchived?'Archived':'Available'}</span></td><td>{x.archivedReason??'—'}</td><td><button className="btn secondary compact" onClick={()=>{setSelected(x);setReason('')}}>{x.isArchived?'Restore':'Archive'}</button></td></tr>)}</tbody></table></div><p className="muted">{archived.length} archived tenants · No tenant records are permanently deleted.</p></main>
 {selected&&<div className="dialog"><section className="card platform-dialog" role="dialog" aria-modal="true"><h2>{selected.isArchived?'Restore':'Archive'} {selected.businessName}</h2><form onSubmit={changeArchive}><div className="platform-warning"><strong>{selected.isArchived?'Restore sign-in eligibility?':'Block tenant access and revoke sessions?'}</strong><p>Restoring does not automatically activate billing. Subscription status must be reviewed separately.</p></div><label>Reason<textarea required minLength={5} maxLength={500} rows={3} value={reason} onChange={x=>setReason(x.target.value)}/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="btn platform-danger-button" disabled={busy}>{busy?'Saving...':'Confirm'}</button></div></form></section></div>}
 {bulkOpen&&<div className="dialog"><section className="card platform-dialog" role="dialog" aria-modal="true"><h2>Archive marked test tenants</h2><form onSubmit={bulkArchive}><div className="platform-warning"><strong>{marked.length} tenants will be archived</strong><p>Real and legacy unmarked tenants cannot be affected by this action.</p></div><label>Reason<textarea required minLength={5} maxLength={500} rows={3} value={reason} onChange={x=>setReason(x.target.value)}/></label><label>Type ARCHIVE TEST TENANTS<input required value={confirmation} onChange={x=>setConfirmation(x.target.value)}/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setBulkOpen(false)}>Cancel</button><button className="btn platform-danger-button" disabled={busy||confirmation!=='ARCHIVE TEST TENANTS'}>{busy?'Archiving...':'Archive test tenants'}</button></div></form></section></div>}</div>
}
