'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {getPlatformSession,platformApi,setPlatformSession} from '@/lib/platform-api';

type Tenant={id:string;businessName:string;email:string;plan:string;status:string;userLimit:number;activeUsers:number;trialEndsAt:string|null;subscriptionEndsAt:string|null;graceEndsAt:string|null;createdAt:string};
type Audit={id:string;platformUserId:string;targetTenantId:string|null;action:string;description:string;correlationId:string;ipAddress:string|null;createdAt:string};
type Edit={tenant:Tenant;plan:string;status:string;userLimit:string;trialEndsAt:string;subscriptionEndsAt:string;graceEndsAt:string;reason:string};
const plans=['Trial','Starter','Growth','Business'];const statuses=['Trialing','Active','PastDue','Suspended','Cancelled','Expired'];
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('en-LK'):'—';
const inputDate=(value:string|null)=>value?new Date(value).toISOString().slice(0,10):'';
const outputDate=(value:string)=>value?new Date(`${value}T23:59:59Z`).toISOString():null;

export default function PlatformTenants(){
 const router=useRouter(),[tenants,setTenants]=useState<Tenant[]>([]),[audit,setAudit]=useState<Audit[]>([]),[view,setView]=useState<'tenants'|'audit'>('tenants'),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('All'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[edit,setEdit]=useState<Edit|null>(null),[confirming,setConfirming]=useState(false),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[tenantRows,auditRows]=await Promise.all([platformApi<Tenant[]>('/tenants'),platformApi<Audit[]>('/audit')]);setTenants(tenantRows);setAudit(auditRows)}catch(x){setError((x as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!getPlatformSession()){router.replace('/platform/login');return}void load()},[load,router]);
 const filtered=useMemo(()=>tenants.filter(x=>(statusFilter==='All'||x.status===statusFilter)&&`${x.businessName} ${x.email}`.toLowerCase().includes(search.toLowerCase())),[tenants,statusFilter,search]);
 const counts=useMemo(()=>({total:tenants.length,active:tenants.filter(x=>x.status==='Active'||x.status==='Trialing').length,pastDue:tenants.filter(x=>x.status==='PastDue').length,suspended:tenants.filter(x=>x.status==='Suspended').length}),[tenants]);
 function open(tenant:Tenant){setEdit({tenant,plan:tenant.plan,status:tenant.status,userLimit:String(tenant.userLimit),trialEndsAt:inputDate(tenant.trialEndsAt),subscriptionEndsAt:inputDate(tenant.subscriptionEndsAt),graceEndsAt:inputDate(tenant.graceEndsAt),reason:''});setConfirming(false)}
 async function save(){if(!edit)return;setSaving(true);setError('');try{await platformApi(`/tenants/${edit.tenant.id}/subscription`,{method:'PUT',body:JSON.stringify({plan:edit.plan,status:edit.status,userLimit:Number(edit.userLimit),trialEndsAt:outputDate(edit.trialEndsAt),subscriptionEndsAt:outputDate(edit.subscriptionEndsAt),graceEndsAt:outputDate(edit.graceEndsAt),reason:edit.reason})});setEdit(null);setConfirming(false);await load()}catch(x){setError((x as Error).message);setConfirming(false)}finally{setSaving(false)}}
 function review(event:FormEvent){event.preventDefault();setConfirming(true)}
 function logout(){setPlatformSession(null);router.replace('/platform/login')}
 return <div className="platform-shell"><header className="platform-top"><div><span className="platform-logo">LankaSaaS</span><span className="platform-console-label">Platform console</span></div><div className="platform-account"><span>{getPlatformSession()?.email}</span><button className="btn secondary compact" onClick={logout}>Sign out</button></div></header><main className="platform-content"><div className="heading"><div><p className="platform-eyebrow">Operator workspace</p><h1>Tenant subscriptions</h1><p className="muted">Control client access without entering or viewing their business records.</p></div><button className="btn secondary" onClick={()=>void load()} disabled={loading}>Refresh</button></div>{error&&<div className="error" role="alert">{error}</div>}
 <section className="platform-metrics"><div className="platform-metric"><span>Total tenants</span><strong>{counts.total}</strong></div><div className="platform-metric"><span>Active or trial</span><strong>{counts.active}</strong></div><div className="platform-metric warning"><span>Past due</span><strong>{counts.pastDue}</strong></div><div className="platform-metric danger"><span>Suspended</span><strong>{counts.suspended}</strong></div></section>
 <div className="platform-tabs" role="tablist"><button className={view==='tenants'?'active':''} onClick={()=>setView('tenants')}>Tenants</button><button className={view==='audit'?'active':''} onClick={()=>setView('audit')}>Audit history</button></div>
 {view==='tenants'?<><div className="platform-toolbar"><input aria-label="Search tenants" placeholder="Search company or email" value={search} onChange={x=>setSearch(x.target.value)}/><select aria-label="Filter by status" value={statusFilter} onChange={x=>setStatusFilter(x.target.value)}><option>All</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></div><div className="table-wrap"><table className="table platform-table"><thead><tr><th>Company</th><th>Plan</th><th>Status</th><th>Users</th><th>Access date</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Loading tenants...</td></tr>:filtered.length?filtered.map(x=><tr key={x.id}><td><strong>{x.businessName}</strong><small>{x.email}</small></td><td>{x.plan}</td><td><span className={`platform-status ${x.status.toLowerCase()}`}>{x.status}</span></td><td>{x.activeUsers} / {x.userLimit}</td><td>{date(x.status==='Trialing'?x.trialEndsAt:x.status==='PastDue'?x.graceEndsAt:x.subscriptionEndsAt)}</td><td><button className="btn secondary compact" onClick={()=>open(x)}>Manage</button></td></tr>):<tr><td colSpan={6}>No tenants match these filters.</td></tr>}</tbody></table></div></>:<div className="table-wrap"><table className="table platform-table"><thead><tr><th>Date</th><th>Action</th><th>Tenant</th><th>Details</th><th>IP</th></tr></thead><tbody>{audit.length?audit.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString('en-LK')}</td><td>{x.action}</td><td>{x.targetTenantId?tenants.find(t=>t.id===x.targetTenantId)?.businessName??x.targetTenantId:'Platform'}</td><td className="audit-description">{x.description}</td><td>{x.ipAddress??'—'}</td></tr>):<tr><td colSpan={5}>No platform activity recorded.</td></tr>}</tbody></table></div>}
 </main>{edit&&<div className="dialog" role="presentation"><section className="card platform-dialog" role="dialog" aria-modal="true" aria-labelledby="manage-title"><div className="dialog-heading"><div><p className="platform-eyebrow">Subscription control</p><h2 id="manage-title">{edit.tenant.businessName}</h2><p className="muted">{edit.tenant.email}</p></div><button className="icon-btn" aria-label="Close" onClick={()=>setEdit(null)}>×</button></div>{!confirming?<form onSubmit={review}><div className="platform-form-grid"><label>Plan<select value={edit.plan} onChange={x=>setEdit({...edit,plan:x.target.value})}>{plans.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={edit.status} onChange={x=>setEdit({...edit,status:x.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>User limit<input type="number" min="1" max="10000" required value={edit.userLimit} onChange={x=>setEdit({...edit,userLimit:x.target.value})}/></label>{edit.status==='Trialing'&&<label>Trial ends<input type="date" required value={edit.trialEndsAt} onChange={x=>setEdit({...edit,trialEndsAt:x.target.value})}/></label>}{['Active','Cancelled'].includes(edit.status)&&<label>Subscription ends<input type="date" value={edit.subscriptionEndsAt} onChange={x=>setEdit({...edit,subscriptionEndsAt:x.target.value})}/></label>}{edit.status==='PastDue'&&<label>Grace period ends<input type="date" required value={edit.graceEndsAt} onChange={x=>setEdit({...edit,graceEndsAt:x.target.value})}/></label>}</div><label>Reason for change<textarea required minLength={5} maxLength={500} rows={3} placeholder="Explain why this subscription is changing" value={edit.reason} onChange={x=>setEdit({...edit,reason:x.target.value})}/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setEdit(null)}>Cancel</button><button className="btn">Review change</button></div></form>:<div className="platform-confirm"><div className="platform-warning"><strong>Confirm subscription change</strong><p>This immediately changes {edit.tenant.businessName} from <b>{edit.tenant.plan} / {edit.tenant.status}</b> to <b>{edit.plan} / {edit.status}</b>.</p>{edit.status==='Suspended'&&<p>The client will retain read access, but all business-data changes will be blocked.</p>}</div><dl><div><dt>User limit</dt><dd>{edit.userLimit}</dd></div><div><dt>Reason</dt><dd>{edit.reason}</dd></div></dl><div className="actions"><button className="btn secondary" onClick={()=>setConfirming(false)} disabled={saving}>Back</button><button className="btn platform-danger-button" onClick={()=>void save()} disabled={saving}>{saving?'Saving...':'Confirm change'}</button></div></div>}</section></div>}</div>
}
