'use client';

import {FormEvent,useEffect,useState} from 'react';
import {api} from '@/lib/api';
import Link from 'next/link';

type Membership={departmentId:string;departmentName:string;departmentCode:string;accessLevel:string;isPrimary:boolean};
type Assignment={departmentId:string;accessLevel:string;isPrimary:boolean};
type User={id:string;firstName:string;lastName:string;email:string;role:string;isActive:boolean;createdAt:string;departments:Membership[]};
type Department={id:string;name:string;code:string;isSystem:boolean;isActive:boolean};

export default function Page(){
 const[users,setUsers]=useState<User[]>([]),[departments,setDepartments]=useState<Department[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<User|null>(null),[resetting,setResetting]=useState<User|null>(null),[assignments,setAssignments]=useState<Assignment[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function load(){try{const[u,d]=await Promise.all([api<User[]>('/users'),api<Department[]>('/departments')]);setUsers(u);setDepartments(d.filter(x=>x.isActive));setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 const defaultDepartment=departments.find(x=>x.code==='GENERAL')?.id??departments[0]?.id??'';
 function initialAssignments(user?:User):Assignment[]{return user?.departments.length?user.departments.map(x=>({departmentId:x.departmentId,accessLevel:x.accessLevel,isPrimary:x.isPrimary})):[{departmentId:defaultDepartment,accessLevel:'Viewer',isPrimary:true}]}
 function startCreate(){setAssignments(initialAssignments());setOpen(true)}
 function startEdit(user:User){setAssignments(initialAssignments(user));setEditing(user)}
 function updateAssignment(index:number,change:Partial<Assignment>){setAssignments(rows=>rows.map((row,i)=>i===index?{...row,...change}:change.isPrimary?{...row,isPrimary:false}:row))}
 function addAssignment(){const available=departments.find(d=>!assignments.some(a=>a.departmentId===d.id));if(available)setAssignments(x=>[...x,{departmentId:available.id,accessLevel:'Viewer',isPrimary:false}])}
 function removeAssignment(index:number){setAssignments(rows=>{const next=rows.filter((_,i)=>i!==index);if(next.length&&!next.some(x=>x.isPrimary))next[0]={...next[0],isPrimary:true};return next})}
 async function assign(userId:string){if(!assignments.length)throw new Error('Assign at least one department.');if(new Set(assignments.map(x=>x.departmentId)).size!==assignments.length)throw new Error('Each department can only be assigned once.');await api(`/users/${userId}/departments`,{method:'PUT',body:JSON.stringify({departments:assignments})})}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{const user=await api<User>('/users',{method:'POST',body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email'),password:f.get('password'),role:f.get('role')})});await assign(user.id);setOpen(false);await load();setSuccess('Team member created and department access assigned.')}catch(x){setError((x as Error).message)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);setError('');try{await api(`/users/${editing.id}`,{method:'PUT',body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),role:f.get('role'),isActive:f.get('isActive')==='on'})});await assign(editing.id);setEditing(null);await load();setSuccess('Team member access updated. They must sign in again to use the new access.')}catch(x){setError((x as Error).message)}}
 async function reset(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!resetting)return;const value=String(new FormData(e.currentTarget).get('newPassword'));try{await api(`/users/${resetting.id}/reset-password`,{method:'POST',body:JSON.stringify({newPassword:value})});setResetting(null);setSuccess('Password updated and existing sessions revoked.')}catch(x){setError((x as Error).message)}}
 const accessFields=<><div className="section-heading"><div><h3>Department access</h3><p className="muted">One department must be the employee&apos;s primary department.</p></div><button type="button" className="btn secondary compact" disabled={assignments.length>=departments.length} onClick={addAssignment}>Add department</button></div><div className="membership-list">{assignments.map((membership,index)=><div className="membership-row" key={`${index}-${membership.departmentId}`}><label>Department<select value={membership.departmentId} required onChange={e=>updateAssignment(index,{departmentId:e.target.value})}>{departments.map(x=><option value={x.id} key={x.id} disabled={assignments.some((a,i)=>i!==index&&a.departmentId===x.id)}>{x.name}</option>)}</select></label><label>Access level<select value={membership.accessLevel} onChange={e=>updateAssignment(index,{accessLevel:e.target.value})}><option value="Viewer">Viewer</option><option value="Member">Member</option><option value="Manager">Manager</option></select></label><label className="check"><input type="radio" name="primaryDepartment" checked={membership.isPrimary} onChange={()=>updateAssignment(index,{isPrimary:true})}/> Primary</label><button type="button" className="danger-link" disabled={assignments.length===1} onClick={()=>removeAssignment(index)}>Remove</button></div>)}</div><p className="muted department-help">Viewer is read-only, Member can perform daily operations, and Manager can approve and manage. Effective access combines all assigned departments.</p></>;
 return <>
  <div className="heading"><div><h1>Team</h1><p className="muted">Manage team members, departments and access levels.</p></div><div className="actions"><Link className="btn secondary" href="/departments">Departments & access</Link><Link className="btn secondary" href="/login-activity">Login activity</Link><button className="btn" onClick={startCreate}>Add team member</button></div></div>
  {error&&<p className="error">{error}</p>}
  <div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Departments</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.firstName} {u.lastName}</strong><br/><span className="muted">{u.role}</span></td><td>{u.email}</td><td><div className="department-chips">{u.departments.map(m=><span className={`department-chip ${m.isPrimary?'primary':''}`} key={m.departmentId}>{m.departmentName} · {u.role==='Admin'?'Administrator':m.accessLevel}{m.isPrimary?' · Primary':''}</span>)}</div></td><td><span className={`badge ${u.isActive?'paid':'cancelled'}`}>{u.isActive?'Active':'Inactive'}</span></td><td><button className="link-button" onClick={()=>startEdit(u)}>Edit access</button><button className="link-button" onClick={()=>setResetting(u)}>Reset password</button></td></tr>)}</tbody></table></div>
  {open&&<div className="dialog"><div className="card team-access-dialog"><div className="dialog-title"><h2>Add team member</h2><button className="icon-btn" onClick={()=>setOpen(false)}>&times;</button></div><form onSubmit={create}><div className="two-fields"><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label></div><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="password" minLength={8} required/></label><label>Account role<select name="role" defaultValue="Staff"><option value="Staff">Team member</option><option value="Admin">Company administrator</option></select></label>{accessFields}<div className="actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn">Create user</button></div></form></div></div>}
  {editing&&<div className="dialog"><div className="card team-access-dialog"><div className="dialog-title"><h2>Edit team member access</h2><button className="icon-btn" onClick={()=>setEditing(null)}>&times;</button></div><form onSubmit={save}><div className="two-fields"><label>First name<input name="firstName" required defaultValue={editing.firstName}/></label><label>Last name<input name="lastName" required defaultValue={editing.lastName}/></label></div><label>Account role<select name="role" defaultValue={editing.role}><option value="Staff">Team member</option><option value="Admin">Company administrator</option></select></label>{accessFields}<label className="check"><input name="isActive" type="checkbox" defaultChecked={editing.isActive}/> Active account</label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn">Save access</button></div></form></div></div>}
  {resetting&&<div className="dialog"><div className="card"><h2>Reset password</h2><p className="muted">Set a temporary password for {resetting.firstName}. Existing sessions will be revoked.</p><form onSubmit={reset}><label>New password<input name="newPassword" type="password" minLength={8} autoComplete="new-password" required/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setResetting(null)}>Cancel</button><button className="btn">Update password</button></div></form></div></div>}
  {success&&<div className="dialog success-dialog"><div className="card"><div className="success-icon">&#10003;</div><h2>Success</h2><p>{success}</p><button className="btn" onClick={()=>setSuccess('')}>OK</button></div></div>}
 </>;
}
