'use client';
import {FormEvent,useEffect,useState} from 'react';
import {api,getSession} from '@/lib/api';
import {useRouter} from 'next/navigation';

type User={id:string;firstName:string;lastName:string;email:string;role:string;isActive:boolean;createdAt:string};
export default function Page(){
 const router=useRouter(),[users,setUsers]=useState<User[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<User|null>(null),[resetting,setResetting]=useState<User|null>(null),[error,setError]=useState('');
 async function load(){try{setUsers(await api<User[]>('/users'))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(getSession()?.user.role!=='Admin')router.replace('/dashboard');else void load()},[router]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api('/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setOpen(false);await load()}catch(x){setError((x as Error).message)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);try{await api(`/users/${editing.id}`,{method:'PUT',body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),role:f.get('role'),isActive:f.get('isActive')==='on'})});setEditing(null);await load()}catch(x){setError((x as Error).message)}}
 async function reset(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!resetting)return;const value=String(new FormData(e.currentTarget).get('newPassword'));try{await api(`/users/${resetting.id}/reset-password`,{method:'POST',body:JSON.stringify({newPassword:value})});setResetting(null)}catch(x){setError((x as Error).message)}}
 return <><div className="heading"><div><h1>Team</h1><p className="muted">Manage who can access this business.</p></div><button className="btn" onClick={()=>setOpen(true)}>Add team member</button></div>{error&&<p className="error">{error}</p>}<table className="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.firstName} {u.lastName}</td><td>{u.email}</td><td>{u.role}</td><td><span className={`badge ${u.isActive?'paid':'cancelled'}`}>{u.isActive?'Active':'Inactive'}</span></td><td><button className="link-button" onClick={()=>setEditing(u)}>Edit</button><button className="link-button" onClick={()=>setResetting(u)}>Reset password</button></td></tr>)}</tbody></table>
 {open&&<div className="dialog"><div className="card"><h2>Add team member</h2><form onSubmit={create}><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="password" minLength={8} required/></label><label>Role<select name="role" defaultValue="Staff"><option>Staff</option><option>Admin</option></select></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn">Create user</button></div></form></div></div>}
 {editing&&<div className="dialog"><div className="card"><h2>Edit team member</h2><form onSubmit={save}><label>First name<input name="firstName" required defaultValue={editing.firstName}/></label><label>Last name<input name="lastName" required defaultValue={editing.lastName}/></label><label>Role<select name="role" defaultValue={editing.role}><option>Staff</option><option>Admin</option></select></label><label className="check"><input name="isActive" type="checkbox" defaultChecked={editing.isActive}/> Active account</label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn">Save changes</button></div></form></div></div>}
 {resetting&&<div className="dialog"><div className="card"><h2>Reset password</h2><p className="muted">Set a temporary password for {resetting.firstName}. Existing sessions will be revoked.</p><form onSubmit={reset}><label>New password<input name="newPassword" type="password" minLength={8} autoComplete="new-password" required/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setResetting(null)}>Cancel</button><button className="btn">Update password</button></div></form></div></div>}</>;
}
