using System.ComponentModel.DataAnnotations;

namespace LankaSaaS.Application;

public record RegisterRequest([Required,MaxLength(120)] string BusinessName,[Required,EmailAddress] string Email,[Required,MinLength(8)] string Password,[Required,MaxLength(60)] string FirstName,[Required,MaxLength(60)] string LastName,string? Phone,string? Address);
public record LoginRequest([Required,EmailAddress] string Email,[Required] string Password);
public record AuthResponse(string AccessToken,DateTimeOffset ExpiresAt,UserDto User);
public record UserDto(Guid Id,string FirstName,string LastName,string Email,string Role,string? ProfilePhotoUrl);
public record DepartmentMembershipDto(Guid DepartmentId,string DepartmentName,string DepartmentCode,string AccessLevel,bool IsPrimary);
public record TeamUserDto(Guid Id,string FirstName,string LastName,string Email,string Role,bool IsActive,DateTimeOffset CreatedAt,string? ProfilePhotoUrl,List<DepartmentMembershipDto> Departments);
public record UserProfileDto(Guid Id,string FirstName,string LastName,string Email,string Role,string? ProfilePhotoUrl);
public record UpdateUserProfileRequest([Url,MaxLength(500)] string? ProfilePhotoUrl);
public record CreateTeamUserRequest([Required,MaxLength(60)] string FirstName,[Required,MaxLength(60)] string LastName,[Required,EmailAddress] string Email,[Required,MinLength(8)] string Password,[Required] string Role);
public record UpdateTeamUserRequest([Required,MaxLength(60)] string FirstName,[Required,MaxLength(60)] string LastName,[Required] string Role,bool IsActive);
public record ResetUserPasswordRequest([Required,MinLength(8)] string NewPassword);
public record DepartmentPermissionDto(string PermissionCode,string MinimumAccessLevel);
public record DepartmentDto(Guid Id,string Name,string Code,bool IsSystem,bool IsActive,List<DepartmentPermissionDto> Permissions);
public record AccessHistoryDto(Guid Id,Guid UserId,string ActorName,string Description,DateTimeOffset CreatedAt);
public record DepartmentRequest([Required,MaxLength(80)] string Name,[Required,RegularExpression("^[A-Za-z][A-Za-z0-9_-]{1,29}$")] string Code,bool IsActive,[Required,MinLength(1)] List<DepartmentPermissionDto> Permissions);
public record UserDepartmentAssignmentRequest(Guid DepartmentId,[Required] string AccessLevel,bool IsPrimary);
public record UpdateUserDepartmentsRequest([Required,MinLength(1)] List<UserDepartmentAssignmentRequest> Departments);
public record CustomerRequest([Required,MaxLength(160)] string Name,string? Phone,[EmailAddress] string? Email,string? Address);
public record CustomerDto(Guid Id,string Name,string? Phone,string? Email,string? Address,DateTimeOffset CreatedAt);
public record ProductRequest([Required,MaxLength(160)] string Name,[Required,MaxLength(80)] string SKU,string? Description,[Range(0,double.MaxValue)] decimal SellingPrice,[Range(0,double.MaxValue)] decimal CostPrice,[Range(0,int.MaxValue)] int StockQuantity,bool IsActive=true);
public record ProductDto(Guid Id,string Name,string SKU,string? Description,decimal SellingPrice,decimal CostPrice,int StockQuantity,bool IsActive,DateTimeOffset CreatedAt);
public record ExpenseRequest([Required,MaxLength(300)] string Description,[Range(0.01,double.MaxValue)] decimal Amount,DateOnly ExpenseDate,[Required,MaxLength(80)] string Category);
public record ExpenseDto(Guid Id,string Description,decimal Amount,DateOnly ExpenseDate,string Category,DateTimeOffset CreatedAt);
public record InvoiceItemRequest(Guid? ProductId,[Required,MaxLength(300)] string Description,[Range(0.01,999999)] decimal Quantity,[Range(0,double.MaxValue)] decimal UnitPrice,[Range(0,double.MaxValue)] decimal Discount,[Range(0,100)] decimal TaxRate);
public record InvoiceRequest(Guid CustomerId,DateOnly IssueDate,DateOnly DueDate,[MaxLength(1000)] string? Notes,[MinLength(1)] List<InvoiceItemRequest> Items);
public record InvoiceStatusRequest([Required] string Status);
public record InvoiceItemDto(Guid Id,Guid? ProductId,string Description,decimal Quantity,decimal UnitPrice,decimal Discount,decimal TaxRate,decimal LineSubtotal,decimal LineTotal);
public record InvoiceDto(Guid Id,string InvoiceNumber,Guid CustomerId,string CustomerName,DateOnly IssueDate,DateOnly DueDate,string Status,decimal Subtotal,decimal DiscountTotal,decimal TaxTotal,decimal Total,string? Notes,List<InvoiceItemDto> Items,DateTimeOffset CreatedAt);
public record InvoiceListDto(Guid Id,string InvoiceNumber,string CustomerName,DateOnly IssueDate,DateOnly DueDate,string Status,decimal Total);
public record DashboardDto(decimal TotalSales,decimal TotalExpenses,int Customers,int Products);
public record CompanySettingsDto(string BusinessName,string Email,string? Phone,string? Address,string? TaxRegistrationNumber,string InvoicePrefix,int NextInvoiceNumber,int DefaultPaymentTermsDays,decimal DefaultTaxRate,string? InvoiceFooter,string? PaymentInstructions,string? LogoUrl);
public record UpdateCompanySettingsRequest([Required,MaxLength(160)] string BusinessName,[Required,EmailAddress] string Email,[MaxLength(40)] string? Phone,[MaxLength(500)] string? Address,[MaxLength(80)] string? TaxRegistrationNumber,[Required,RegularExpression("^[A-Za-z0-9-]{1,12}$")] string InvoicePrefix,[Range(0,365)] int DefaultPaymentTermsDays,[Range(0,100)] decimal DefaultTaxRate,[MaxLength(500)] string? InvoiceFooter,[MaxLength(1000)] string? PaymentInstructions,[Url,MaxLength(500)] string? LogoUrl);
public record LoginActivityUserDto(Guid UserId,string Name,string Email,long TotalLogins,DateTimeOffset? LastLoginAt);
public record RecentLoginDto(Guid Id,Guid UserId,string Name,string Email,DateTimeOffset LoggedInAt);
public record LoginActivityDto(long TotalLogins,int LoginsLast30Days,int ActiveUsersLast30Days,List<LoginActivityUserDto> Users,List<RecentLoginDto> RecentLogins);
public record SubscriptionPlanDto(string Code,string Name,decimal MonthlyPriceLkr,int UserLimit,string Description);
public record BillingTransactionDto(Guid Id,string Reference,string Plan,decimal Amount,string Currency,string Status,string? PaymentMethod,DateTimeOffset CreatedAt);
public record SubscriptionDto(string Plan,string Status,int UserLimit,int ActiveUsers,int RemainingUserSeats,DateTimeOffset? TrialEndsAt,DateTimeOffset? SubscriptionEndsAt,DateTimeOffset? CancellationRequestedAt,List<SubscriptionPlanDto> AvailablePlans,List<BillingTransactionDto> BillingHistory);
public record CreateSubscriptionCheckoutRequest([Required] string Plan,[Required,MaxLength(40)] string Phone,[Required,MaxLength(300)] string Address,[Required,MaxLength(80)] string City);
public record PaymentCheckoutDto(string ActionUrl,Dictionary<string,string> Fields);
public record SubscriptionAccessDto(string Status,bool IsReadOnly,string Message,DateTimeOffset? AccessEndsAt);
public record PlatformLoginRequest([Required,EmailAddress] string Email,[Required] string Password);
public record PlatformAuthResponse(string AccessToken,DateTimeOffset ExpiresAt,string Email,string Role);
public record PlatformTenantDto(Guid Id,string BusinessName,string Email,string Plan,string Status,int UserLimit,int ActiveUsers,DateTimeOffset? TrialEndsAt,DateTimeOffset? SubscriptionEndsAt,DateTimeOffset? GraceEndsAt,bool IsTestTenant,bool IsArchived,DateTimeOffset? ArchivedAt,string? ArchivedReason,DateTimeOffset CreatedAt);
public record PlatformSubscriptionUpdateRequest([Required] string Plan,[Required] string Status,[Range(1,10000)] int UserLimit,DateTimeOffset? TrialEndsAt,DateTimeOffset? SubscriptionEndsAt,DateTimeOffset? GraceEndsAt,[Required,MinLength(5),MaxLength(500)] string Reason);
public record PlatformSubscriptionPlanDto(string Code,string Name,decimal MonthlyPriceLkr,int UserLimit,string Description,bool IsActive,DateTimeOffset UpdatedAt);
public record UpdatePlatformSubscriptionPlanRequest([Required,MaxLength(80)] string Name,[Range(0.01,double.MaxValue)] decimal MonthlyPriceLkr,[Range(1,10000)] int UserLimit,[Required,MaxLength(300)] string Description,bool IsActive,[Required,MinLength(5),MaxLength(500)] string Reason);
public record PlatformAuditEventDto(Guid Id,Guid PlatformUserId,Guid? TargetTenantId,string Action,string Description,string CorrelationId,string? IpAddress,DateTimeOffset CreatedAt);
public record PlatformUserDto(Guid Id,string Email,string Role,bool IsActive,DateTimeOffset? LastLoginAt,DateTimeOffset CreatedAt);
public record CreatePlatformUserRequest([Required,EmailAddress] string Email,[Required,MinLength(12),MaxLength(200)] string Password);
public record UpdatePlatformUserAccessRequest(bool IsActive,[Required,MinLength(5),MaxLength(500)] string Reason);
public record ChangePlatformPasswordRequest([Required] string CurrentPassword,[Required,MinLength(12),MaxLength(200)] string NewPassword);
public record ArchiveTenantRequest(bool IsArchived,[Required,MinLength(5),MaxLength(500)] string Reason);
public record ArchiveTestTenantsRequest([Required] string Confirmation,[Required,MinLength(5),MaxLength(500)] string Reason);
public record EventRequest(Guid CustomerId,[Required,MaxLength(160)] string Name,[Required,MaxLength(300)] string Venue,DateTimeOffset StartsAt,DateTimeOffset EndsAt,[Required] string Status,[Range(0,double.MaxValue)] decimal BudgetedRevenue,[Range(0,double.MaxValue)] decimal BudgetedCost,[MaxLength(2000)] string? Notes,bool RequireLocationForAttendance=false,double? Latitude=null,double? Longitude=null,[Range(25,2000)] int AttendanceRadiusMeters=150,[Range(10,5000)] int MaximumLocationAccuracyMeters=100,[Range(0,1440)] int CheckInWindowMinutes=60);
public record EventExpenseRequest([Required,MaxLength(300)] string Description,[Required,MaxLength(80)] string Category,[Range(0.01,double.MaxValue)] decimal Amount,DateOnly ExpenseDate);
public record EventExpenseDto(Guid Id,string Description,string Category,decimal Amount,DateOnly ExpenseDate,bool IsGenerated);
public record EventDto(Guid Id,Guid CustomerId,string CustomerName,string Name,string Venue,DateTimeOffset StartsAt,DateTimeOffset EndsAt,string Status,decimal BudgetedRevenue,decimal BudgetedCost,decimal ActualCost,decimal ForecastProfit,string? Notes,bool RequireLocationForAttendance,double? Latitude,double? Longitude,int AttendanceRadiusMeters,int MaximumLocationAccuracyMeters,int CheckInWindowMinutes,List<EventExpenseDto> Expenses);
public record LogisticsResourceRequest([Required,MaxLength(160)] string Name,[Required] string Type,[MaxLength(100)] string? Identifier,[Range(1,100000)] int TotalQuantity,[Required] string Status,[MaxLength(1000)] string? Notes);
public record LogisticsResourceDto(Guid Id,string Name,string Type,string? Identifier,int TotalQuantity,string Status,string? Notes);
public record AllocationRequest(Guid ResourceId,[Range(1,100000)] int Quantity);
public record ReturnAllocationRequest([Range(0,100000)] int ReturnedQuantity,[Range(0,100000)] int DamagedQuantity,[Range(0,100000)] int MissingQuantity);
public record AllocationDto(Guid Id,Guid EventId,Guid ResourceId,string ResourceName,int Quantity,string Status,int ReturnedQuantity,int DamagedQuantity,int MissingQuantity);
public record ChecklistRequest([Required,MaxLength(300)] string Description);
public record ChecklistDto(Guid Id,Guid EventId,string Description,bool IsCompleted,DateTimeOffset? CompletedAt);
public record SupplierRequest([Required,MaxLength(160)] string Name,[MaxLength(120)] string? ContactName,[MaxLength(40)] string? Phone,[EmailAddress] string? Email,[MaxLength(500)] string? Address);
public record SupplierDto(Guid Id,string Name,string? ContactName,string? Phone,string? Email,string? Address);
public record PurchaseOrderItemRequest(Guid? ResourceId,[Required,MaxLength(300)] string Description,[Range(0.01,100000)] decimal Quantity,[Range(0,double.MaxValue)] decimal UnitCost);
public record PurchaseOrderRequest(Guid SupplierId,Guid? EventId,[Required] string Type,DateOnly OrderDate,DateOnly? RentalStartDate,DateOnly? RentalEndDate,[MaxLength(1000)] string? Notes,[MinLength(1)] List<PurchaseOrderItemRequest> Items);
public record SupplierPaymentRequest([Range(0.01,double.MaxValue)] decimal Amount,DateOnly PaymentDate,[Required,MaxLength(40)] string Method,[MaxLength(100)] string? Reference);
public record PurchaseOrderDto(Guid Id,Guid SupplierId,string SupplierName,Guid? EventId,string Type,string Status,DateOnly OrderDate,DateOnly? RentalStartDate,DateOnly? RentalEndDate,decimal Total,decimal Paid,decimal Outstanding,string? Notes,List<PurchaseOrderItemRequest> Items);
public record QuotationItemRequest([Required,MaxLength(300)] string Description,[Range(0.01,100000)] decimal Quantity,[Range(0,double.MaxValue)] decimal UnitPrice);
public record EventQuotationRequest(DateOnly IssueDate,DateOnly ValidUntil,[Range(0,double.MaxValue)] decimal DepositRequired,[MaxLength(1000)] string? Notes,[MinLength(1)] List<QuotationItemRequest> Items);
public record CustomerPaymentRequest([Range(0.01,double.MaxValue)] decimal Amount,DateOnly PaymentDate,[Required,MaxLength(40)] string Method,[MaxLength(100)] string? Reference,bool IsDeposit);
public record EventQuotationDto(Guid Id,string QuotationNumber,string Status,DateOnly IssueDate,DateOnly ValidUntil,decimal Total,decimal DepositRequired,string? Notes,List<QuotationItemRequest> Items);
public record EventFinanceDto(Guid EventId,string EventName,decimal QuotedRevenue,decimal Invoiced,decimal Received,decimal Receivable,decimal ActualCost,decimal ActualProfit,List<EventQuotationDto> Quotations,List<InvoiceListDto> Invoices);
public record LedgerAccountDto(Guid Id,string Code,string Name,string Type,bool IsSystem,bool IsActive,decimal Balance);
public record ManualJournalLineRequest(Guid AccountId,[Range(0,double.MaxValue)] decimal Debit,[Range(0,double.MaxValue)] decimal Credit);
public record ManualJournalRequest(DateOnly EntryDate,[Required,MaxLength(300)] string Description,[MaxLength(100)] string? Reference,Guid? EventId,[MinLength(2)] List<ManualJournalLineRequest> Lines);
public record JournalLineDto(string AccountCode,string AccountName,decimal Debit,decimal Credit);
public record JournalEntryDto(Guid Id,DateOnly EntryDate,string Description,string? Reference,Guid? EventId,string SourceType,List<JournalLineDto> Lines);
public record ProfitLossDto(DateOnly From,DateOnly To,decimal Revenue,decimal Expenses,decimal NetProfit);
public record StaffingUserDto(Guid Id,string Name,string Role);
public record StaffAssignmentRequest(Guid UserId,[Required,MaxLength(120)] string Responsibility,DateTimeOffset ShiftStartsAt,DateTimeOffset ShiftEndsAt,[Range(0,double.MaxValue)] decimal HourlyRate,[MaxLength(500)] string? Notes);
public record AttendanceRequest(double? Latitude,double? Longitude,[Range(0,10000)] double? AccuracyMeters,bool IsOverride=false,[MaxLength(500)] string? OverrideReason=null);
public record StaffAssignmentDto(Guid Id,Guid EventId,Guid UserId,string StaffName,string Responsibility,DateTimeOffset ShiftStartsAt,DateTimeOffset ShiftEndsAt,decimal HourlyRate,decimal PlannedHours,decimal PlannedCost,string Status,DateTimeOffset? CheckedInAt,DateTimeOffset? CheckedOutAt,decimal ActualHours,decimal ActualCost,string? Notes);
public record EventAttendancePolicyDto(bool RequireLocation,double? Latitude,double? Longitude,int RadiusMeters,int MaximumAccuracyMeters,int CheckInWindowMinutes);
public record EventStaffingDto(Guid EventId,string EventName,decimal PlannedLabourCost,decimal ActualLabourCost,EventAttendancePolicyDto AttendancePolicy,List<StaffAssignmentDto> Assignments);
public record EventReportRowDto(Guid EventId,string EventName,string CustomerName,string Status,DateTimeOffset StartsAt,decimal BudgetedRevenue,decimal InvoicedRevenue,decimal ReceivedRevenue,decimal BudgetedCost,decimal ActualCost,decimal LabourCost,decimal Receivable,decimal Payable,decimal Profit,decimal MarginPercent,int AssignedStaff,int AllocatedResourceQuantity);
public record EventReportingDto(DateOnly From,DateOnly To,int EventCount,decimal BudgetedRevenue,decimal InvoicedRevenue,decimal ReceivedRevenue,decimal BudgetedCost,decimal ActualCost,decimal Receivables,decimal Payables,decimal Profit,decimal QuotationConversionPercent,decimal LogisticsUtilizationPercent,decimal PlannedLabourCost,decimal ActualLabourCost,List<EventReportRowDto> Events);
public record EventReportExportDto(string FileName,string Content);
public record AuditEventDto(Guid Id,Guid UserId,string Method,string Path,int StatusCode,string CorrelationId,string? IpAddress,DateTimeOffset CreatedAt);

public interface ITenantContext { Guid TenantId { get; } Guid UserId { get; } bool IsAuthenticated { get; } }
