using System.ComponentModel.DataAnnotations;

namespace LankaSaaS.Application;

public record RegisterRequest([Required,MaxLength(120)] string BusinessName,[Required,EmailAddress] string Email,[Required,MinLength(8)] string Password,[Required,MaxLength(60)] string FirstName,[Required,MaxLength(60)] string LastName,string? Phone,string? Address);
public record LoginRequest([Required,EmailAddress] string Email,[Required] string Password);
public record AuthResponse(string AccessToken,DateTimeOffset ExpiresAt,UserDto User);
public record UserDto(Guid Id,string FirstName,string LastName,string Email,string Role);
public record TeamUserDto(Guid Id,string FirstName,string LastName,string Email,string Role,bool IsActive,DateTimeOffset CreatedAt);
public record CreateTeamUserRequest([Required,MaxLength(60)] string FirstName,[Required,MaxLength(60)] string LastName,[Required,EmailAddress] string Email,[Required,MinLength(8)] string Password,[Required] string Role);
public record UpdateTeamUserRequest([Required,MaxLength(60)] string FirstName,[Required,MaxLength(60)] string LastName,[Required] string Role,bool IsActive);
public record ResetUserPasswordRequest([Required,MinLength(8)] string NewPassword);
public record CustomerRequest([Required,MaxLength(160)] string Name,string? Phone,[EmailAddress] string? Email,string? Address);
public record CustomerDto(Guid Id,string Name,string? Phone,string? Email,string? Address,DateTimeOffset CreatedAt);
public record ProductRequest([Required,MaxLength(160)] string Name,[Required,MaxLength(80)] string SKU,string? Description,[Range(0,double.MaxValue)] decimal SellingPrice,[Range(0,double.MaxValue)] decimal CostPrice,[Range(0,int.MaxValue)] int StockQuantity,bool IsActive=true);
public record ProductDto(Guid Id,string Name,string SKU,string? Description,decimal SellingPrice,decimal CostPrice,int StockQuantity,bool IsActive,DateTimeOffset CreatedAt);
public record ExpenseRequest([Required,MaxLength(300)] string Description,[Range(0.01,double.MaxValue)] decimal Amount,DateOnly ExpenseDate,[Required,MaxLength(80)] string Category);
public record ExpenseDto(Guid Id,string Description,decimal Amount,DateOnly ExpenseDate,string Category,DateTimeOffset CreatedAt);
public record InvoiceItemRequest(Guid? ProductId,[Required,MaxLength(300)] string Description,[Range(0.01,999999)] decimal Quantity,[Range(0,double.MaxValue)] decimal UnitPrice,[Range(0,double.MaxValue)] decimal Discount,[Range(0,100)] decimal TaxRate);
public record InvoiceRequest(Guid CustomerId,DateOnly IssueDate,DateOnly DueDate,[MaxLength(1000)] string? Notes,[MinLength(1)] List<InvoiceItemRequest> Items);
public record InvoiceStatusRequest([Required] string Status);
public record InvoiceItemDto(Guid Id,Guid? ProductId,string Description,decimal Quantity,decimal UnitPrice,decimal Discount,decimal TaxRate,decimal LineSubtotal,decimal LineTotal);
public record InvoiceDto(Guid Id,string InvoiceNumber,Guid CustomerId,string CustomerName,DateOnly IssueDate,DateOnly DueDate,string Status,decimal Subtotal,decimal DiscountTotal,decimal TaxTotal,decimal Total,string? Notes,List<InvoiceItemDto> Items,DateTimeOffset CreatedAt);
public record InvoiceListDto(Guid Id,string InvoiceNumber,string CustomerName,DateOnly IssueDate,DateOnly DueDate,string Status,decimal Total);
public record DashboardDto(decimal TotalSales,decimal TotalExpenses,int Customers,int Products);
public record CompanySettingsDto(string BusinessName,string Email,string? Phone,string? Address,string? TaxRegistrationNumber,string InvoicePrefix,int NextInvoiceNumber,int DefaultPaymentTermsDays,decimal DefaultTaxRate,string? InvoiceFooter,string? PaymentInstructions,string? LogoUrl);
public record UpdateCompanySettingsRequest([Required,MaxLength(160)] string BusinessName,[Required,EmailAddress] string Email,[MaxLength(40)] string? Phone,[MaxLength(500)] string? Address,[MaxLength(80)] string? TaxRegistrationNumber,[Required,RegularExpression("^[A-Za-z0-9-]{1,12}$")] string InvoicePrefix,[Range(0,365)] int DefaultPaymentTermsDays,[Range(0,100)] decimal DefaultTaxRate,[MaxLength(500)] string? InvoiceFooter,[MaxLength(1000)] string? PaymentInstructions,[Url,MaxLength(500)] string? LogoUrl);
public record LoginActivityUserDto(Guid UserId,string Name,string Email,long TotalLogins,DateTimeOffset? LastLoginAt);
public record RecentLoginDto(Guid Id,Guid UserId,string Name,string Email,DateTimeOffset LoggedInAt);
public record LoginActivityDto(long TotalLogins,int LoginsLast30Days,int ActiveUsersLast30Days,List<LoginActivityUserDto> Users,List<RecentLoginDto> RecentLogins);
public record SubscriptionPlanDto(string Code,string Name,decimal MonthlyPriceLkr,int UserLimit,string Description);
public record BillingTransactionDto(Guid Id,string Reference,string Plan,decimal Amount,string Currency,string Status,string? PaymentMethod,DateTimeOffset CreatedAt);
public record SubscriptionDto(string Plan,string Status,int UserLimit,int ActiveUsers,int RemainingUserSeats,DateTimeOffset? TrialEndsAt,DateTimeOffset? SubscriptionEndsAt,DateTimeOffset? CancellationRequestedAt,List<SubscriptionPlanDto> AvailablePlans,List<BillingTransactionDto> BillingHistory);
public record CreateSubscriptionCheckoutRequest([Required] string Plan,[Required,MaxLength(40)] string Phone,[Required,MaxLength(300)] string Address,[Required,MaxLength(80)] string City);
public record PaymentCheckoutDto(string ActionUrl,Dictionary<string,string> Fields);
public record SubscriptionAccessDto(string Status,bool IsReadOnly,string Message,DateTimeOffset? AccessEndsAt);
public record EventRequest(Guid CustomerId,[Required,MaxLength(160)] string Name,[Required,MaxLength(300)] string Venue,DateTimeOffset StartsAt,DateTimeOffset EndsAt,[Required] string Status,[Range(0,double.MaxValue)] decimal BudgetedRevenue,[Range(0,double.MaxValue)] decimal BudgetedCost,[MaxLength(2000)] string? Notes);
public record EventExpenseRequest([Required,MaxLength(300)] string Description,[Required,MaxLength(80)] string Category,[Range(0.01,double.MaxValue)] decimal Amount,DateOnly ExpenseDate);
public record EventExpenseDto(Guid Id,string Description,string Category,decimal Amount,DateOnly ExpenseDate);
public record EventDto(Guid Id,Guid CustomerId,string CustomerName,string Name,string Venue,DateTimeOffset StartsAt,DateTimeOffset EndsAt,string Status,decimal BudgetedRevenue,decimal BudgetedCost,decimal ActualCost,decimal ForecastProfit,string? Notes,List<EventExpenseDto> Expenses);
public record LogisticsResourceRequest([Required,MaxLength(160)] string Name,[Required] string Type,[MaxLength(100)] string? Identifier,[Range(1,100000)] int TotalQuantity,[Required] string Status,[MaxLength(1000)] string? Notes);
public record LogisticsResourceDto(Guid Id,string Name,string Type,string? Identifier,int TotalQuantity,string Status,string? Notes);
public record AllocationRequest(Guid ResourceId,[Range(1,100000)] int Quantity);
public record ReturnAllocationRequest([Range(0,100000)] int ReturnedQuantity,[Range(0,100000)] int DamagedQuantity,[Range(0,100000)] int MissingQuantity);
public record AllocationDto(Guid Id,Guid EventId,Guid ResourceId,string ResourceName,int Quantity,string Status,int ReturnedQuantity,int DamagedQuantity,int MissingQuantity);
public record ChecklistRequest([Required,MaxLength(300)] string Description);
public record ChecklistDto(Guid Id,Guid EventId,string Description,bool IsCompleted,DateTimeOffset? CompletedAt);
public record SupplierRequest([Required,MaxLength(160)] string Name,[MaxLength(120)] string? ContactName,[MaxLength(40)] string? Phone,[EmailAddress] string? Email,[MaxLength(500)] string? Address);
public record SupplierDto(Guid Id,string Name,string? ContactName,string? Phone,string? Email,string? Address);
public record PurchaseOrderItemRequest(Guid? ResourceId,[Required,MaxLength(300)] string Description,[Range(0.01,100000)] decimal Quantity,[Range(0,double.MaxValue)] decimal UnitCost);
public record PurchaseOrderRequest(Guid SupplierId,Guid? EventId,[Required] string Type,DateOnly OrderDate,DateOnly? RentalStartDate,DateOnly? RentalEndDate,[MaxLength(1000)] string? Notes,[MinLength(1)] List<PurchaseOrderItemRequest> Items);
public record SupplierPaymentRequest([Range(0.01,double.MaxValue)] decimal Amount,DateOnly PaymentDate,[Required,MaxLength(40)] string Method,[MaxLength(100)] string? Reference);
public record PurchaseOrderDto(Guid Id,Guid SupplierId,string SupplierName,Guid? EventId,string Type,string Status,DateOnly OrderDate,DateOnly? RentalStartDate,DateOnly? RentalEndDate,decimal Total,decimal Paid,decimal Outstanding,string? Notes,List<PurchaseOrderItemRequest> Items);
public record QuotationItemRequest([Required,MaxLength(300)] string Description,[Range(0.01,100000)] decimal Quantity,[Range(0,double.MaxValue)] decimal UnitPrice);
public record EventQuotationRequest(DateOnly IssueDate,DateOnly ValidUntil,[Range(0,double.MaxValue)] decimal DepositRequired,[MaxLength(1000)] string? Notes,[MinLength(1)] List<QuotationItemRequest> Items);
public record CustomerPaymentRequest([Range(0.01,double.MaxValue)] decimal Amount,DateOnly PaymentDate,[Required,MaxLength(40)] string Method,[MaxLength(100)] string? Reference,bool IsDeposit);
public record EventQuotationDto(Guid Id,string QuotationNumber,string Status,DateOnly IssueDate,DateOnly ValidUntil,decimal Total,decimal DepositRequired,string? Notes,List<QuotationItemRequest> Items);
public record EventFinanceDto(Guid EventId,string EventName,decimal QuotedRevenue,decimal Invoiced,decimal Received,decimal Receivable,decimal ActualCost,decimal ActualProfit,List<EventQuotationDto> Quotations,List<InvoiceListDto> Invoices);
public record LedgerAccountDto(Guid Id,string Code,string Name,string Type,bool IsSystem,bool IsActive,decimal Balance);
public record ManualJournalLineRequest(Guid AccountId,[Range(0,double.MaxValue)] decimal Debit,[Range(0,double.MaxValue)] decimal Credit);
public record ManualJournalRequest(DateOnly EntryDate,[Required,MaxLength(300)] string Description,[MaxLength(100)] string? Reference,Guid? EventId,[MinLength(2)] List<ManualJournalLineRequest> Lines);
public record JournalLineDto(string AccountCode,string AccountName,decimal Debit,decimal Credit);
public record JournalEntryDto(Guid Id,DateOnly EntryDate,string Description,string? Reference,Guid? EventId,string SourceType,List<JournalLineDto> Lines);
public record ProfitLossDto(DateOnly From,DateOnly To,decimal Revenue,decimal Expenses,decimal NetProfit);

public interface ITenantContext { Guid TenantId { get; } Guid UserId { get; } bool IsAuthenticated { get; } }
