'use client';

import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {money} from '@/lib/invoices';

type Event={id:string;name:string;startsAt:string};
type QuoteItem={description:string;quantity:number;unitPrice:number};
type Quote={id:string;quotationNumber:string;status:string;issueDate:string;validUntil:string;total:number;depositRequired:number;notes?:string;items:QuoteItem[]};
type Invoice={id:string;invoiceNumber:string;status:string;total:number;paid:number;outstanding:number};
type Finance={eventName:string;quotedRevenue:number;invoiced:number;received:number;receivable:number;actualCost:number;actualProfit:number;quotations:Quote[];invoices:Invoice[]};

export default function Page(){
  const[events,setEvents]=useState<Event[]>([]),[eventId,setEventId]=useState(''),[data,setData]=useState<Finance|null>(null);
  const[editingQuote,setEditingQuote]=useState<Quote|null>(null),[deletingQuote,setDeletingQuote]=useState<Quote|null>(null),[paymentInvoice,setPaymentInvoice]=useState<Invoice|null>(null);
  const[success,setSuccess]=useState(''),[error,setError]=useState(''),[paymentError,setPaymentError]=useState('');

  useEffect(()=>{api<Event[]>('/events').then(events=>{setEvents(events);const requested=new URLSearchParams(window.location.search).get('eventId');if(requested&&events.some(x=>x.id===requested))void load(requested)}).catch(e=>setError(e.message))},[]);
  async function load(id:string){setEventId(id);setData(id?await api<Finance>(`/events/${id}/finance`):null)}
  async function quote(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=Object.fromEntries(new FormData(form));setError('');setSuccess('');try{await api(`/events/${eventId}/finance/quotations`,{method:'POST',body:JSON.stringify({issueDate:f.issueDate,validUntil:f.validUntil,depositRequired:+f.depositRequired,notes:f.notes,items:[{description:f.description,quantity:+f.quantity,unitPrice:+f.unitPrice}]})});form.reset();await load(eventId);setSuccess('Quotation created successfully.')}catch(x){setError((x as Error).message)}}
  async function updateQuote(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editingQuote)return;const f=Object.fromEntries(new FormData(e.currentTarget));setError('');try{await api(`/events/${eventId}/finance/quotations/${editingQuote.id}`,{method:'PUT',body:JSON.stringify({issueDate:f.issueDate,validUntil:f.validUntil,depositRequired:+f.depositRequired,notes:f.notes,items:[{description:f.description,quantity:+f.quantity,unitPrice:+f.unitPrice}]})});setEditingQuote(null);await load(eventId);setSuccess('Quotation updated successfully.')}catch(x){setError((x as Error).message)}}
  async function removeQuote(){if(!deletingQuote)return;setError('');try{await api(`/events/${eventId}/finance/quotations/${deletingQuote.id}`,{method:'DELETE'});setDeletingQuote(null);await load(eventId);setSuccess('Draft quotation deleted successfully.')}catch(x){setDeletingQuote(null);setError((x as Error).message)}}
  async function status(q:Quote,value:string){await api(`/events/${eventId}/finance/quotations/${q.id}/status/${value}`,{method:'PATCH'});await load(eventId)}
  async function convert(q:Quote){await api(`/events/${eventId}/finance/quotations/${q.id}/convert`,{method:'POST'});await load(eventId)}
  async function recordPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!paymentInvoice)return;const f=Object.fromEntries(new FormData(e.currentTarget)),amount=Number(f.amount),amountCents=Math.round(amount*100),outstandingCents=Math.round(paymentInvoice.outstanding*100);setError('');setPaymentError('');if(!Number.isFinite(amount)||amountCents<=0){setPaymentError('Enter a payment amount greater than zero.');return}if(amountCents>outstandingCents){setPaymentError(`Payment cannot exceed the remaining balance of ${money(outstandingCents/100)}.`);return}try{await api(`/events/${eventId}/finance/invoices/${paymentInvoice.id}/payments`,{method:'POST',body:JSON.stringify({amount:amountCents/100,paymentDate:f.paymentDate,method:f.method,reference:String(f.reference||'').trim()||null,isDeposit:f.isDeposit==='on'})});setPaymentInvoice(null);await load(eventId);setSuccess(`Payment recorded successfully for ${paymentInvoice.invoiceNumber}.`)}catch(x){setPaymentError((x as Error).message)}}

  return <>
    <div className="heading"><div><h1>Event finance</h1><p className="muted">Move from quotation to invoice, deposits, balances and actual profit.</p></div></div>
    {error&&<p className="error">{error}</p>}
    <label>Select event<select value={eventId} onChange={e=>void load(e.target.value)}><option value="">Choose event</option>{events.map(x=><option key={x.id} value={x.id}>{x.name} — {new Date(x.startsAt).toLocaleDateString()}</option>)}</select></label>
    {data&&<>
      <div className="grid" style={{marginTop:20}}><Metric label="Accepted quotes" value={data.quotedRevenue}/><Metric label="Invoiced" value={data.invoiced}/><Metric label="Received" value={data.received}/><Metric label="Receivable" value={data.receivable}/><Metric label="Actual cost" value={data.actualCost}/><Metric label="Cash profit" value={data.actualProfit}/></div>
      <div className="logistics-grid" style={{marginTop:20}}>
        <div className="card"><h2>New quotation</h2><form onSubmit={quote}><label>Issue date<input name="issueDate" type="date" required/></label><label>Valid until<input name="validUntil" type="date" required/></label><input name="description" aria-label="Service or package" placeholder="Service or package" required/><input name="quantity" aria-label="Quantity" type="number" min="0.01" step="0.01" placeholder="Quantity" required/><input name="unitPrice" aria-label="Unit price (LKR)" type="number" min="0" step="0.01" placeholder="Unit price (LKR)" required/><input name="depositRequired" aria-label="Required deposit (LKR)" type="number" min="0" step="0.01" placeholder="Required deposit (LKR)" required/><textarea name="notes" aria-label="Terms or notes" placeholder="Terms or notes"/><button className="btn">Create quotation</button></form></div>
        <div className="card"><h2>Quotations</h2><table className="table"><tbody>{data.quotations.map(q=><tr key={q.id}><td>{q.quotationNumber}<br/><span className="muted">{q.status}</span></td><td>{money(q.total)}</td><td>{q.status==='Draft'&&<div className="quote-actions"><button className="link-button" onClick={()=>setEditingQuote(q)}>Edit</button><button className="danger-link" onClick={()=>setDeletingQuote(q)}>Delete</button><button className="link-button" onClick={()=>status(q,'Sent')}>Send</button></div>}{q.status==='Sent'&&<><button className="link-button" onClick={()=>status(q,'Accepted')}>Accept</button><button className="link-button" onClick={()=>status(q,'Rejected')}>Reject</button></>}{q.status==='Accepted'&&<button className="link-button" onClick={()=>convert(q)}>Create invoice</button>}</td></tr>)}</tbody></table></div>
      </div>
      <h2 style={{marginTop:28}}>Event invoices</h2><table className="table"><thead><tr><th>Invoice</th><th>Status</th><th>Total</th><th>Balance</th><th>Action</th></tr></thead><tbody>{data.invoices.map(x=><tr key={x.id}><td><Link className="link" href={`/invoices/${x.id}`}>{x.invoiceNumber}</Link></td><td>{x.status}</td><td>{money(x.total)}</td><td>{money(x.outstanding)}</td><td>{x.status!=='Paid'&&x.status!=='Cancelled'&&<button className="link-button" onClick={()=>{setError('');setPaymentError('');setPaymentInvoice(x)}}>Record payment</button>}</td></tr>)}</tbody></table>
    </>}
    {editingQuote&&<div className="dialog" role="dialog" aria-modal="true" aria-labelledby="quote-edit-title"><div className="card"><div className="dialog-title"><h2 id="quote-edit-title">Edit draft quotation</h2><button className="icon-btn" type="button" onClick={()=>setEditingQuote(null)}>&times;</button></div><form onSubmit={updateQuote}><label>Issue date<input name="issueDate" type="date" required defaultValue={editingQuote.issueDate}/></label><label>Valid until<input name="validUntil" type="date" required defaultValue={editingQuote.validUntil}/></label><label>Service or package<input name="description" required defaultValue={editingQuote.items[0]?.description}/></label><label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" required defaultValue={editingQuote.items[0]?.quantity}/></label><label>Unit price (LKR)<input name="unitPrice" type="number" min="0" step="0.01" required defaultValue={editingQuote.items[0]?.unitPrice}/></label><label>Required deposit (LKR)<input name="depositRequired" type="number" min="0" step="0.01" required defaultValue={editingQuote.depositRequired}/></label><label>Terms or notes<textarea name="notes" defaultValue={editingQuote.notes}/></label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setEditingQuote(null)}>Cancel</button><button className="btn">Save changes</button></div></form></div></div>}
    {deletingQuote&&<div className="dialog confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="quote-delete-title"><div className="card"><div className="warning-icon" aria-hidden="true">!</div><h2 id="quote-delete-title">Delete draft quotation?</h2><p><strong>{deletingQuote.quotationNumber}</strong> for {money(deletingQuote.total)} will be permanently deleted.</p><div className="actions"><button className="btn secondary" onClick={()=>setDeletingQuote(null)}>Cancel</button><button className="btn danger" onClick={()=>void removeQuote()}>Delete quotation</button></div></div></div>}
    {paymentInvoice&&<div className="dialog" role="dialog" aria-modal="true" aria-labelledby="payment-title"><div className="card payment-dialog"><div className="dialog-title"><div><span className="eyebrow">Customer payment</span><h2 id="payment-title">Record payment</h2><p className="muted">{paymentInvoice.invoiceNumber} · Invoice total {money(paymentInvoice.total)}</p><p><strong>Remaining balance: {money(paymentInvoice.outstanding)}</strong></p></div><button className="icon-btn" type="button" aria-label="Close" onClick={()=>setPaymentInvoice(null)}>&times;</button></div>{paymentError&&<p className="error" role="alert">{paymentError}</p>}<form onSubmit={recordPayment}><label>Amount received (LKR)<input name="amount" type="number" min="0.01" max={paymentInvoice.outstanding.toFixed(2)} step="0.01" placeholder={paymentInvoice.outstanding.toFixed(2)} autoFocus required/></label><div className="two-fields"><label>Payment date<input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Payment method<select name="method" defaultValue="Bank transfer"><option>Bank transfer</option><option>Cash</option><option>Card</option><option>Cheque</option><option>Online payment</option></select></label></div><label>Reference (optional)<input name="reference" placeholder="Receipt or transaction number"/></label><label className="check"><input name="isDeposit" type="checkbox" defaultChecked={paymentInvoice.status==='Draft'}/>Record as deposit</label><div className="actions"><button type="button" className="btn secondary" onClick={()=>setPaymentInvoice(null)}>Cancel</button><button className="btn">Record payment</button></div></form></div></div>}
    {success&&<div className="dialog success-dialog" role="dialog" aria-modal="true" aria-labelledby="finance-success-title"><div className="card"><div className="success-icon" aria-hidden="true">✓</div><h2 id="finance-success-title">Success</h2><p>{success}</p><button className="btn" autoFocus onClick={()=>setSuccess('')}>OK</button></div></div>}
  </>
}

function Metric({label,value}:{label:string,value:number}){return <div className="card metric"><span className="muted">{label}</span><strong>{money(value)}</strong></div>}
