'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api,getSession} from '@/lib/api';

type NextEvent={id:string;name:string;venue:string;startsAt:string;status:string};
type Trend={month:string;revenue:number;expenses:number};
type Data={totalSales:number;totalExpenses:number;customers:number;products:number;nextEvent:NextEvent|null;upcomingEvents:number;incompleteChecklistItems:number;overdueInvoices:number;outstandingReceivables:number;trends:Trend[]};
const money=(value:number)=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR',maximumFractionDigits:0}).format(value);
function countdown(value:string,now:number){const difference=new Date(value).getTime()-now;if(difference<=0)return'Event is starting now';const days=Math.floor(difference/86400000),hours=Math.floor(difference%86400000/3600000),minutes=Math.floor(difference%3600000/60000);return days>0?`${days}d ${hours}h remaining`:hours>0?`${hours}h ${minutes}m remaining`:`${Math.max(1,minutes)}m remaining`}

export default function Dashboard(){
 const[d,setD]=useState<Data|null>(null),[error,setError]=useState(''),[now,setNow]=useState(()=>Date.now());
 const admin=getSession()?.user.role==='Admin';
 useEffect(()=>{api<Data>('/dashboard').then(setD).catch(e=>setError(e.message));const timer=window.setInterval(()=>setNow(Date.now()),60000);return()=>window.clearInterval(timer)},[]);
 const cards=d?[{label:'Sales',value:money(d.totalSales),note:'Recorded customer revenue',tone:'revenue',icon:'↗'},{label:'Expenses',value:money(d.totalExpenses),note:'Recorded business costs',tone:'expense',icon:'↘'},{label:'Customers',value:String(d.customers),note:'Customer records',tone:'contacts',icon:'C'},{label:'Products',value:String(d.products),note:'Active catalogue items',tone:'stock',icon:'P'}]:[];
 const chartMax=Math.max(1,...(d?.trends.flatMap(x=>[x.revenue,x.expenses])||[1]));
 return <div className="dashboard-page">
  <div className="heading dashboard-heading"><div><span className="eyebrow">Operations overview</span><h1>Good day{getSession()?.user.firstName?`, ${getSession()?.user.firstName}`:''}</h1><p className="muted">Start with today&apos;s event operations and financial follow-ups.</p></div></div>
  {error&&<p className="error">{error}</p>}
  {!d&&!error?<div className="grid dashboard-metrics">{[1,2,3,4].map(x=><div className="card metric loading-metric" key={x}><span className="muted">Loading…</span><strong>—</strong></div>)}</div>:<div className="grid dashboard-metrics">{cards.map(card=><div className={`card metric metric-${card.tone}`} key={card.label}><div className="metric-heading"><span>{card.label}</span><span className="metric-icon" aria-hidden="true">{card.icon}</span></div><strong>{card.value}</strong><small className="muted">{card.note}</small></div>)}</div>}
  {d&&<section className="section dashboard-focus-grid">
   <article className="panel next-event-card"><div className="section-heading"><div><span className="eyebrow">Coming up</span><h2>Next event</h2></div><span className="badge info">{d.nextEvent?.status||'No event'}</span></div>{d.nextEvent?<><h3>{d.nextEvent.name}</h3><p className="muted">{d.nextEvent.venue} · {new Date(d.nextEvent.startsAt).toLocaleString()}</p><strong className="countdown">{countdown(d.nextEvent.startsAt,now)}</strong><Link className="btn" href={`/events?eventId=${d.nextEvent.id}`}>Open event</Link></>:<div className="empty compact-empty"><p className="muted">No upcoming events are currently scheduled.</p><Link className="btn" href="/events?new=1">Create event</Link></div>}</article>
   <article className="panel reminder-panel"><div className="section-heading"><div><span className="eyebrow">Attention</span><h2>Reminders</h2></div></div><div className="reminder-list"><Link href="/events"><span className="reminder-count">{d.upcomingEvents}</span><span><strong>Upcoming events</strong><small>Scheduled within the next 30 days</small></span></Link><Link href="/logistics"><span className={`reminder-count ${d.incompleteChecklistItems?'warning':''}`}>{d.incompleteChecklistItems}</span><span><strong>Checklist tasks</strong><small>Still incomplete for upcoming events</small></span></Link><Link href="/invoices"><span className={`reminder-count ${d.overdueInvoices?'danger':''}`}>{d.overdueInvoices}</span><span><strong>Overdue invoices</strong><small>{money(d.outstandingReceivables)} total outstanding</small></span></Link></div></article>
  </section>}
  {d&&<section className="section panel dashboard-chart"><div className="section-heading"><div><span className="eyebrow">Last six months</span><h2>Revenue and expenses</h2><p className="muted">Paid invoices compared with recorded business expenses.</p></div><div className="chart-legend"><span><i className="revenue"/>Revenue</span><span><i className="expense"/>Expenses</span></div></div><div className="bar-chart" role="img" aria-label="Revenue and expenses for the last six months">{d.trends.map(point=><div className="chart-period" key={point.month}><div className="chart-bars"><span className="bar revenue" style={{height:`${Math.max(point.revenue?5:1,point.revenue/chartMax*100)}%`}} title={`${point.month} revenue ${money(point.revenue)}`}/><span className="bar expense" style={{height:`${Math.max(point.expenses?5:1,point.expenses/chartMax*100)}%`}} title={`${point.month} expenses ${money(point.expenses)}`}/></div><span>{point.month}</span></div>)}</div></section>}
  <section className="section dashboard-quick-section"><div className="section-heading"><div><span className="eyebrow">Shortcuts</span><h2>Quick actions</h2><p className="muted">Common tasks without hunting through menus.</p></div></div><div className="quick-actions"><Link className="btn" href="/events?new=1">Create event</Link><Link className="btn secondary" href="/customers">Add customer</Link><Link className="btn secondary" href="/event-staffing">Attendance</Link><Link className="btn secondary" href="/logistics">Dispatch & returns</Link><Link className="btn secondary" href="/event-finance">Event finance</Link></div></section>
  <section className="section"><div className="panel"><div className="section-heading"><div><h2>Operations checklist</h2><p className="muted">A simple rhythm for every event day.</p></div></div><div className="dashboard-checklist"><Link href="/event-staffing"><strong>1. Confirm staff</strong><span>Review assignments and on-site check-ins</span></Link><Link href="/logistics"><strong>2. Confirm logistics</strong><span>Review dispatches, returns and shortages</span></Link><Link href="/event-finance"><strong>3. Review money</strong><span>Record deposits, costs and supplier payments</span></Link><Link href="/event-reports"><strong>4. Review outcome</strong><span>Check event profit and outstanding balances</span></Link></div></div></section>
  {admin&&<section className="section"><div className="panel"><div className="section-heading"><div><h2>Administration</h2><p className="muted">Manage access and company configuration.</p></div></div><div className="quick-actions"><Link className="btn secondary" href="/team">Manage team</Link><Link className="btn secondary" href="/settings">Company settings</Link><Link className="btn secondary" href="/subscription">Subscription</Link></div></div></section>}
 </div>;
}
