'use client';
import {FormEvent,useEffect,useState} from 'react';
import {api,getSession} from '@/lib/api';
import {CompanySettings} from '@/lib/invoices';
import {useRouter} from 'next/navigation';

export default function Page(){
 const router=useRouter(),[settings,setSettings]=useState<CompanySettings|null>(null),[logoUrl,setLogoUrl]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(getSession()?.user.role!=='Admin')router.replace('/dashboard');else api<CompanySettings>('/settings').then(x=>{setSettings(x);setLogoUrl(x.logoUrl||'')}).catch(e=>setError(e.message))},[router]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));try{const result=await api<CompanySettings>('/settings',{method:'PUT',body:JSON.stringify({...form,defaultPaymentTermsDays:Number(form.defaultPaymentTermsDays),defaultTaxRate:Number(form.defaultTaxRate),logoUrl:logoUrl||null})});setSettings(result);setLogoUrl(result.logoUrl||'');window.dispatchEvent(new Event('branding-updated'));setMessage('Settings saved. The company branding is now visible throughout the application.');setError('')}catch(err){setError((err as Error).message)}}
 if(!settings)return <p className={error?'error':'muted'}>{error||'Loading settings…'}</p>;
 return <><div className="heading"><div><h1>Company settings</h1><p className="muted">Business identity, tenant branding and invoice defaults.</p></div></div>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}<form onSubmit={save}><div className="card settings-grid"><label>Business name<input name="businessName" required defaultValue={settings.businessName}/></label><label>Business email<input name="email" type="email" required defaultValue={settings.email}/></label><label>Phone<input name="phone" defaultValue={settings.phone}/></label><label>Tax registration number<input name="taxRegistrationNumber" defaultValue={settings.taxRegistrationNumber}/></label><label className="wide">Address<textarea name="address" rows={3} defaultValue={settings.address}/></label><div className="wide branding-editor"><div className="logo-preview">{logoUrl?<img src={logoUrl} alt="Company logo preview" onError={e=>{e.currentTarget.style.display='none'}}/>:<span>{settings.businessName.slice(0,1).toUpperCase()}</span>}</div><label>Company logo HTTPS URL<input type="url" value={logoUrl} onChange={e=>setLogoUrl(e.target.value)} placeholder="https://example.com/company-logo.png" maxLength={500}/><small className="muted">Shown in the sidebar and on invoices. A transparent PNG or square logo works best.</small></label></div><label>Invoice prefix<input name="invoicePrefix" required maxLength={12} defaultValue={settings.invoicePrefix}/></label><label>Next invoice number<input value={settings.nextInvoiceNumber} disabled/><small className="muted">Managed automatically</small></label><label>Payment terms (days)<input name="defaultPaymentTermsDays" type="number" min="0" max="365" required defaultValue={settings.defaultPaymentTermsDays}/></label><label>Default tax %<input name="defaultTaxRate" type="number" min="0" max="100" step="0.01" required defaultValue={settings.defaultTaxRate}/></label><label className="wide">Payment instructions<textarea name="paymentInstructions" rows={3} defaultValue={settings.paymentInstructions}/></label><label className="wide">Invoice footer<textarea name="invoiceFooter" rows={3} defaultValue={settings.invoiceFooter}/></label></div><div className="actions"><button className="btn">Save settings</button></div></form></>;
}
